// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaxVision.Tasks.Infrastructure.Persistence;

#nullable disable

namespace TaxVision.Tasks.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TasksDbContext))]
    [Migration("20260814032141_AddClientRequests")]
    partial class AddClientRequests
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaxVision.Tasks.Domain.Backfill.TenantBackfillState", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("TenantId");

                    b.ToTable("TenantBackfillStates", (string)null);
                });

            modelBuilder.Entity("TaxVision.Tasks.Domain.ClientRequests.ClientRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Details")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime?>("DueAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RequestedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ResolutionNote")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("ResolvedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ResolvedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SubmittedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "TaskId")
                        .HasDatabaseName("IX_ClientRequests_TenantId_TaskId");

                    b.HasIndex("TenantId", "CustomerId", "Status")
                        .HasDatabaseName("IX_ClientRequests_TenantId_CustomerId_Status");

                    b.ToTable("ClientRequests", (string)null);
                });

            modelBuilder.Entity("TaxVision.Tasks.Domain.ClientRequests.ClientRequestDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentType")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("ResolvedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FileId")
                        .HasDatabaseName("IX_ClientRequestDocuments_FileId");

                    b.HasIndex("ClientRequestId", "FileId")
                        .IsUnique()
                        .HasDatabaseName("UX_ClientRequestDocuments_RequestId_FileId_Active")
                        .HasFilter("[Status] <> 4");

                    b.ToTable("ClientRequestDocuments", (string)null);
                });

            modelBuilder.Entity("TaxVision.Tasks.Domain.Dependencies.TaskDependency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DependsOnTaskId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "DependsOnTaskId");

                    b.HasIndex("TenantId", "TaskId", "DependsOnTaskId")
                        .IsUnique();

                    b.ToTable("TaskDependencies", (string)null);
                });

            modelBuilder.Entity("TaxVision.Tasks.Domain.Labels.TaskLabel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("MapsToStatus")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("UX_TaskLabels_TenantId_Code");

                    b.ToTable("TaskLabels", (string)null);
                });

            modelBuilder.Entity("TaxVision.Tasks.Domain.Permissions.RolePermissionsProjection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PermissionCodesJson")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("PermissionsVersion")
                        .HasColumnType("int");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("RolePermissionsProjections", (string)null);
                });

            modelBuilder.Entity("TaxVision.Tasks.Domain.Permissions.UserPermissionsProjection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PermissionCodesJson")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("PermissionsVersion")
                        .HasColumnType("int");

                    b.Property<string>("RoleIdsJson")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "IsActive");

                    b.HasIndex("TenantId", "UserId")
                        .IsUnique();

                    b.ToTable("UserPermissionsProjections", (string)null);
                });

            modelBuilder.Entity("TaxVision.Tasks.Domain.Projections.CustomerDirectoryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "CustomerId")
                        .IsUnique()
                        .HasDatabaseName("IX_CustomerDirectoryEntries_TenantId_CustomerId");

                    b.HasIndex("TenantId", "DisplayName")
                        .HasDatabaseName("IX_CustomerDirectoryEntries_TenantId_DisplayName");

                    b.ToTable("CustomerDirectoryEntries", (string)null);
                });

            modelBuilder.Entity("TaxVision.Tasks.Domain.RateLimiting.TenantPlanCodeProjection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PlanCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("RevisionNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .IsUnique();

                    b.ToTable("TenantPlanCodeProjections", (string)null);
                });

            modelBuilder.Entity("TaxVision.Tasks.Domain.Series.TaskSeries", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AnchorUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("EndsAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("GeneratedCount")
                        .HasColumnType("int");

                    b.Property<int?>("MaxOccurrences")
                        .HasColumnType("int");

                    b.Property<int>("Mode")
                        .HasColumnType("int");

                    b.Property<Guid?>("OpenInstanceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SkippedOccurrences")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("IX_TaskSeries_TenantId_Status");

                    b.ToTable("TaskSeries", (string)null);
                });

            modelBuilder.Entity("TaxVision.Tasks.Domain.Tasks.TaskAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AttachedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("AttachedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentType")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<DateTime?>("DetachedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Origin")
                        .HasColumnType("int");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TaskId", "FileId")
                        .IsUnique()
                        .HasDatabaseName("UX_TaskAttachments_TaskId_FileId_Active")
                        .HasFilter("[Status] <> 4");

                    b.HasIndex("TenantId", "FileId")
                        .HasDatabaseName("IX_TaskAttachments_TenantId_FileId");

                    b.ToTable("TaskAttachments", (string)null);
                });

            modelBuilder.Entity("TaxVision.Tasks.Domain.Tasks.TaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ActualHours")
                        .HasColumnType("decimal(8,2)");

                    b.Property<Guid?>("AssigneeUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ClientDueAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ClientRequestedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ClientRequestedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Depth")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(8000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Estimated")
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("ExpectedItems")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("ExpectedItems");

                    b.Property<int?>("OccurrenceNumber")
                        .HasColumnType("int");

                    b.Property<int>("OpenBlockerCount")
                        .HasColumnType("int");

                    b.Property<int>("OpenSubtaskCount")
                        .HasColumnType("int");

                    b.Property<Guid?>("ParentTaskId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid?>("SeriesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ParentTaskId")
                        .HasDatabaseName("IX_Tasks_TenantId_ParentTaskId");

                    b.HasIndex("TenantId", "SeriesId")
                        .HasDatabaseName("IX_Tasks_TenantId_SeriesId");

                    b.HasIndex("TenantId", "TemplateId")
                        .HasDatabaseName("IX_Tasks_TenantId_TemplateId");

                    b.HasIndex("TenantId", "Status", "ClientDueAtUtc")
                        .HasDatabaseName("IX_Tasks_TenantId_Status_ClientDueAtUtc_WaitingOnClient")
                        .HasFilter("[Status] = 3");

                    b.ToTable("Tasks", (string)null);
                });

            modelBuilder.Entity("TaxVision.Tasks.Domain.Tasks.TaskTimer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsBillable")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StoppedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.HasIndex("UserId", "StartedAtUtc")
                        .HasDatabaseName("IX_TaskTimers_UserId_StartedAtUtc");

                    b.ToTable("TaskTimers", (string)null);
                });

            modelBuilder.Entity("TaxVision.Tasks.Domain.Templates.TaskTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("RecurrenceMode")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "IsActive")
                        .HasDatabaseName("IX_TaskTemplates_TenantId_IsActive");

                    b.ToTable("TaskTemplates", (string)null);
                });

            modelBuilder.Entity("TaxVision.Tasks.Domain.Templates.TaskTemplateAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentType")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int?>("StepOrder")
                        .HasColumnType("int");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId", "FileId")
                        .IsUnique()
                        .HasDatabaseName("UX_TaskTemplateAttachments_TemplateId_FileId");

                    b.ToTable("TaskTemplateAttachments", (string)null);
                });

            modelBuilder.Entity("TaxVision.Tasks.Domain.Templates.TaskTemplateStep", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("DependsOnStepOrder")
                        .HasColumnType("int");

                    b.Property<int>("DueOffsetDays")
                        .HasColumnType("int");

                    b.Property<bool>("IsStatutory")
                        .HasColumnType("bit");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int?>("ParentStepOrder")
                        .HasColumnType("int");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("SuggestedRoleName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("TaskTemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TaskTemplateId", "Order")
                        .IsUnique()
                        .HasDatabaseName("UX_TaskTemplateSteps_TemplateId_Order");

                    b.ToTable("TaskTemplateSteps", (string)null);
                });

            modelBuilder.Entity("TaxVision.Tasks.Infrastructure.Persistence.ReadModels.TaskDependencyEdge", b =>
                {
                    b.Property<Guid>("DependsOnTaskId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uniqueidentifier");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("TaxVision.Tasks.Domain.ClientRequests.ClientRequestDocument", b =>
                {
                    b.HasOne("TaxVision.Tasks.Domain.ClientRequests.ClientRequest", null)
                        .WithMany("Documents")
                        .HasForeignKey("ClientRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TaxVision.Tasks.Domain.Series.TaskSeries", b =>
                {
                    b.OwnsOne("TaxVision.Tasks.Domain.Series.TaskItemBlueprint", "Blueprint", b1 =>
                        {
                            b1.Property<Guid>("TaskSeriesId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("AssigneeUserId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("AssigneeUserId");

                            b1.Property<string>("Description")
                                .HasMaxLength(8000)
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Description");

                            b1.Property<decimal?>("Estimated")
                                .HasColumnType("decimal(6,2)")
                                .HasColumnName("EstimatedHours");

                            b1.Property<bool>("IsStatutory")
                                .HasColumnType("bit")
                                .HasColumnName("IsStatutory");

                            b1.Property<int>("Priority")
                                .HasColumnType("int")
                                .HasColumnName("Priority");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Title");

                            b1.HasKey("TaskSeriesId");

                            b1.ToTable("TaskSeries");

                            b1.WithOwner()
                                .HasForeignKey("TaskSeriesId");

                            b1.OwnsOne("TaxVision.Tasks.Domain.ValueObjects.TaskReference", "Reference", b2 =>
                                {
                                    b2.Property<Guid>("TaskItemBlueprintTaskSeriesId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<Guid?>("CustomerId")
                                        .HasColumnType("uniqueidentifier")
                                        .HasColumnName("CustomerId");

                                    b2.Property<int?>("TaxYear")
                                        .HasColumnType("int")
                                        .HasColumnName("TaxYear");

                                    b2.HasKey("TaskItemBlueprintTaskSeriesId");

                                    b2.ToTable("TaskSeries");

                                    b2.WithOwner()
                                        .HasForeignKey("TaskItemBlueprintTaskSeriesId");
                                });

                            b1.Navigation("Reference")
                                .IsRequired();
                        });

                    b.OwnsOne("TaxVision.Tasks.Domain.ValueObjects.RecurrenceRule", "Rule", b1 =>
                        {
                            b1.Property<Guid>("TaskSeriesId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("TimeZoneId")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("RecurrenceTimeZoneId");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("RecurrenceRule");

                            b1.HasKey("TaskSeriesId");

                            b1.ToTable("TaskSeries");

                            b1.WithOwner()
                                .HasForeignKey("TaskSeriesId");
                        });

                    b.Navigation("Blueprint")
                        .IsRequired();

                    b.Navigation("Rule")
                        .IsRequired();
                });

            modelBuilder.Entity("TaxVision.Tasks.Domain.Tasks.TaskAttachment", b =>
                {
                    b.HasOne("TaxVision.Tasks.Domain.Tasks.TaskItem", null)
                        .WithMany("Attachments")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TaxVision.Tasks.Domain.Tasks.TaskItem", b =>
                {
                    b.OwnsOne("TaxVision.Tasks.Domain.ValueObjects.TaskReference", "Reference", b1 =>
                        {
                            b1.Property<Guid>("TaskItemId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid?>("CustomerId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("CustomerId");

                            b1.Property<int?>("TaxYear")
                                .HasColumnType("int")
                                .HasColumnName("TaxYear");

                            b1.HasKey("TaskItemId");

                            b1.ToTable("Tasks");

                            b1.WithOwner()
                                .HasForeignKey("TaskItemId");
                        });

                    b.OwnsOne("TaxVision.Tasks.Domain.ValueObjects.TaskTitle", "Title", b1 =>
                        {
                            b1.Property<Guid>("TaskItemId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Title");

                            b1.HasKey("TaskItemId");

                            b1.ToTable("Tasks");

                            b1.WithOwner()
                                .HasForeignKey("TaskItemId");
                        });

                    b.OwnsOne("TaxVision.Tasks.Domain.ValueObjects.DueDate", "Due", b1 =>
                        {
                            b1.Property<Guid>("TaskItemId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("DueAtUtc")
                                .HasColumnType("datetime2")
                                .HasColumnName("DueAtUtc");

                            b1.Property<bool>("IsStatutory")
                                .HasColumnType("bit")
                                .HasColumnName("DueIsStatutory");

                            b1.Property<string>("TimeZoneId")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("DueTimeZoneId");

                            b1.HasKey("TaskItemId");

                            b1.ToTable("Tasks");

                            b1.WithOwner()
                                .HasForeignKey("TaskItemId");
                        });

                    b.Navigation("Due");

                    b.Navigation("Reference")
                        .IsRequired();

                    b.Navigation("Title")
                        .IsRequired();
                });

            modelBuilder.Entity("TaxVision.Tasks.Domain.Tasks.TaskTimer", b =>
                {
                    b.HasOne("TaxVision.Tasks.Domain.Tasks.TaskItem", null)
                        .WithMany("Timers")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TaxVision.Tasks.Domain.Templates.TaskTemplate", b =>
                {
                    b.OwnsOne("TaxVision.Tasks.Domain.ValueObjects.RecurrenceRule", "Recurrence", b1 =>
                        {
                            b1.Property<Guid>("TaskTemplateId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("TimeZoneId")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("RecurrenceTimeZoneId");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("RecurrenceRule");

                            b1.HasKey("TaskTemplateId");

                            b1.ToTable("TaskTemplates");

                            b1.WithOwner()
                                .HasForeignKey("TaskTemplateId");
                        });

                    b.Navigation("Recurrence");
                });

            modelBuilder.Entity("TaxVision.Tasks.Domain.Templates.TaskTemplateAttachment", b =>
                {
                    b.HasOne("TaxVision.Tasks.Domain.Templates.TaskTemplate", null)
                        .WithMany("Attachments")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TaxVision.Tasks.Domain.Templates.TaskTemplateStep", b =>
                {
                    b.HasOne("TaxVision.Tasks.Domain.Templates.TaskTemplate", null)
                        .WithMany("Steps")
                        .HasForeignKey("TaskTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("TaxVision.Tasks.Domain.ValueObjects.TaskTitle", "Title", b1 =>
                        {
                            b1.Property<Guid>("TaskTemplateStepId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Title");

                            b1.HasKey("TaskTemplateStepId");

                            b1.ToTable("TaskTemplateSteps");

                            b1.WithOwner()
                                .HasForeignKey("TaskTemplateStepId");
                        });

                    b.OwnsOne("TaxVision.Tasks.Domain.ValueObjects.EstimatedHours", "Estimated", b1 =>
                        {
                            b1.Property<Guid>("TaskTemplateStepId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Value")
                                .HasPrecision(6, 2)
                                .HasColumnType("decimal(6,2)")
                                .HasColumnName("EstimatedHours");

                            b1.HasKey("TaskTemplateStepId");

                            b1.ToTable("TaskTemplateSteps");

                            b1.WithOwner()
                                .HasForeignKey("TaskTemplateStepId");
                        });

                    b.OwnsOne("TaxVision.Tasks.Domain.ValueObjects.TaskDescription", "Description", b1 =>
                        {
                            b1.Property<Guid>("TaskTemplateStepId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(8000)
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Description");

                            b1.HasKey("TaskTemplateStepId");

                            b1.ToTable("TaskTemplateSteps");

                            b1.WithOwner()
                                .HasForeignKey("TaskTemplateStepId");
                        });

                    b.Navigation("Description");

                    b.Navigation("Estimated");

                    b.Navigation("Title")
                        .IsRequired();
                });

            modelBuilder.Entity("TaxVision.Tasks.Domain.ClientRequests.ClientRequest", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("TaxVision.Tasks.Domain.Tasks.TaskItem", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Timers");
                });

            modelBuilder.Entity("TaxVision.Tasks.Domain.Templates.TaskTemplate", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
