// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaxVision.Subscription.Infrastructure.Persistence;

#nullable disable

namespace TaxVision.Subscription.Infrastructure.Migrations
{
    [DbContext(typeof(SubscriptionDbContext))]
    [Migration("20260629012401_UpdateSubscriptionSchema")]
    partial class UpdateSubscriptionSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaxVision.Subscription.Domain.Billing.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DiscountCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("DiscountPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("InvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsSystemGenerated")
                        .HasColumnType("bit");

                    b.Property<string>("Metadata")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("PaidDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("PaymentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PaymentMethodId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentProviderId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SubTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("TaxAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TransactionNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("TransactionStatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TransactionTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TransactionNumber")
                        .IsUnique();

                    b.HasIndex("TransactionStatusId");

                    b.HasIndex("TransactionTypeId");

                    b.ToTable("Transactions", (string)null);
                });

            modelBuilder.Entity("TaxVision.Subscription.Domain.Billing.TransactionDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsProrated")
                        .HasColumnType("bit");

                    b.Property<string>("ItemDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Metadata")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid?>("PricingItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ProrationEndDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("ProrationFactor")
                        .HasPrecision(10, 6)
                        .HasColumnType("decimal(10,6)");

                    b.Property<DateTime?>("ProrationStartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("RemainingDays")
                        .HasColumnType("int");

                    b.Property<decimal>("SubTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TotalDaysInPeriod")
                        .HasColumnType("int");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("TransactionId");

                    b.ToTable("TransactionDetails", (string)null);
                });

            modelBuilder.Entity("TaxVision.Subscription.Domain.Billing.TransactionHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChangedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("FromStatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("ToStatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TransactionId");

                    b.ToTable("TransactionHistories", (string)null);
                });

            modelBuilder.Entity("TaxVision.Subscription.Domain.Billing.TransactionStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFinal")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("TransactionStatuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            Code = "PENDING",
                            Color = "warning",
                            Description = "Transacción creada, pendiente de procesamiento",
                            IsActive = true,
                            IsFinal = false,
                            Name = "Pendiente",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000002"),
                            Code = "PROCESSING",
                            Color = "info",
                            Description = "Transacción en proceso de pago",
                            IsActive = true,
                            IsFinal = false,
                            Name = "Procesando",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000003"),
                            Code = "COMPLETED",
                            Color = "success",
                            Description = "Transacción completada exitosamente",
                            IsActive = true,
                            IsFinal = true,
                            Name = "Completada",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000004"),
                            Code = "FAILED",
                            Color = "danger",
                            Description = "Transacción fallida",
                            IsActive = true,
                            IsFinal = true,
                            Name = "Fallida",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000005"),
                            Code = "REFUNDED",
                            Color = "secondary",
                            Description = "Transacción reembolsada completamente",
                            IsActive = true,
                            IsFinal = true,
                            Name = "Reembolsada",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000006"),
                            Code = "CANCELLED",
                            Color = "secondary",
                            Description = "Transacción cancelada",
                            IsActive = true,
                            IsFinal = true,
                            Name = "Cancelada",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000007"),
                            Code = "PARTIAL_REFUND",
                            Color = "warning",
                            Description = "Transacción con reembolso parcial",
                            IsActive = true,
                            IsFinal = false,
                            Name = "Reembolso Parcial",
                            SortOrder = 7
                        });
                });

            modelBuilder.Entity("TaxVision.Subscription.Domain.Billing.TransactionType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("TransactionTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            Code = "SUBSCRIPTION",
                            Description = "Pago de suscripción inicial",
                            IsActive = true,
                            Name = "Suscripción Inicial",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            Code = "RENEWAL",
                            Description = "Renovación de suscripción",
                            IsActive = true,
                            Name = "Renovación",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            Code = "USER_INCREASE",
                            Description = "Aumento de límite de usuarios",
                            IsActive = true,
                            Name = "Aumento de Usuarios",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000004"),
                            Code = "MODULE_ADD",
                            Description = "Adición de módulo adicional",
                            IsActive = true,
                            Name = "Adición de Módulo",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000005"),
                            Code = "UPGRADE",
                            Description = "Actualización a un plan superior",
                            IsActive = true,
                            Name = "Upgrade de Plan",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000006"),
                            Code = "DOWNGRADE",
                            Description = "Cambio a un plan inferior",
                            IsActive = true,
                            Name = "Downgrade de Plan",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000007"),
                            Code = "ONE_TIME",
                            Description = "Cargo único o extraordinario",
                            IsActive = true,
                            Name = "Cargo Único",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000008"),
                            Code = "REFUND",
                            Description = "Reembolso de pago",
                            IsActive = true,
                            Name = "Reembolso",
                            SortOrder = 8
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000009"),
                            Code = "PRORATED",
                            Description = "Ajuste prorrateado por cambios en el plan",
                            IsActive = true,
                            Name = "Ajuste Prorrateado",
                            SortOrder = 9
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000010"),
                            Code = "BILLING_PERIOD_CHANGE",
                            Description = "Cambio de período de facturación (mensual ↔ anual)",
                            IsActive = true,
                            Name = "Cambio de Período",
                            SortOrder = 10
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000011"),
                            Code = "PLAN_UPGRADE_WITH_PERIOD_CHANGE",
                            Description = "Actualización de plan y cambio de período simultáneos",
                            IsActive = true,
                            Name = "Upgrade con Cambio de Período",
                            SortOrder = 11
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000012"),
                            Code = "PLAN_MODIFICATION",
                            Description = "Modificación general del plan",
                            IsActive = true,
                            Name = "Modificación de Plan",
                            SortOrder = 12
                        });
                });

            modelBuilder.Entity("TaxVision.Subscription.Domain.Enrollments.SubscriptionEnrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdminEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("BillingPeriod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrgName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PlanCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProvisionedTenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Subdomain")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("TaxVision.Subscription.Domain.Modules.Module", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Url")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("TaxVision.Subscription.Domain.Modules.PlanModule", b =>
                {
                    b.Property<Guid>("PlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ModuleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PlanId", "ModuleId");

                    b.HasIndex("ModuleId");

                    b.HasIndex("PlanId");

                    b.ToTable("PlanModules", (string)null);
                });

            modelBuilder.Entity("TaxVision.Subscription.Domain.Plans.Plan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("BasePriceAnnual")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<decimal>("BasePriceMonthly")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("IncludedSeats")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PricePerAdditionalSeat")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<int>("ServiceLevel")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Plans");
                });

            modelBuilder.Entity("TaxVision.Subscription.Domain.Plans.PlanFeature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FeatureCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PlanId", "FeatureCode")
                        .IsUnique();

                    b.ToTable("PlanFeatures");
                });

            modelBuilder.Entity("TaxVision.Subscription.Domain.Pricing.PricingHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("NewPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OldPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("PricingItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("PricingItemId");

                    b.ToTable("PricingHistories", (string)null);
                });

            modelBuilder.Entity("TaxVision.Subscription.Domain.Pricing.PricingItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AnnualPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("bit");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MaxQuantity")
                        .HasColumnType("int");

                    b.Property<string>("Metadata")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("MinQuantity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("PricingItemTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemCode")
                        .IsUnique();

                    b.HasIndex("PricingItemTypeId");

                    b.ToTable("PricingItems", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            AnnualPrice = 400m,
                            Description = "Precio por usuario para planes de 1-5 usuarios",
                            IsActive = true,
                            IsRecurring = true,
                            ItemCode = "USER_LIMIT_STARTER",
                            MaxQuantity = 5,
                            MinQuantity = 1,
                            Name = "Usuario - Tier Starter",
                            PricingItemTypeId = new Guid("10000000-0000-0000-0000-000000000001"),
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111112"),
                            AnnualPrice = 350m,
                            Description = "Precio por usuario para planes de 6-20 usuarios",
                            IsActive = true,
                            IsRecurring = true,
                            ItemCode = "USER_LIMIT_BUSINESS",
                            MaxQuantity = 20,
                            MinQuantity = 6,
                            Name = "Usuario - Tier Business",
                            PricingItemTypeId = new Guid("10000000-0000-0000-0000-000000000001"),
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111113"),
                            AnnualPrice = 300m,
                            Description = "Precio por usuario para planes de 21-50 usuarios",
                            IsActive = true,
                            IsRecurring = true,
                            ItemCode = "USER_LIMIT_PROFESSIONAL",
                            MaxQuantity = 50,
                            MinQuantity = 21,
                            Name = "Usuario - Tier Professional",
                            PricingItemTypeId = new Guid("10000000-0000-0000-0000-000000000001"),
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111114"),
                            AnnualPrice = 250m,
                            Description = "Precio por usuario para planes de 51-100 usuarios",
                            IsActive = true,
                            IsRecurring = true,
                            ItemCode = "USER_LIMIT_ENTERPRISE",
                            MaxQuantity = 100,
                            MinQuantity = 51,
                            Name = "Usuario - Tier Enterprise",
                            PricingItemTypeId = new Guid("10000000-0000-0000-0000-000000000001"),
                            SortOrder = 4
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111115"),
                            AnnualPrice = 200m,
                            Description = "Precio por usuario para planes de 101+ usuarios",
                            IsActive = true,
                            IsRecurring = true,
                            ItemCode = "USER_LIMIT_ENTERPRISE_PLUS",
                            MaxQuantity = 999999,
                            MinQuantity = 101,
                            Name = "Usuario - Tier Enterprise Plus",
                            PricingItemTypeId = new Guid("10000000-0000-0000-0000-000000000001"),
                            SortOrder = 5
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222221"),
                            AnnualPrice = 1200m,
                            Description = "Sistema avanzado de gestión de inventario con trazabilidad completa",
                            IsActive = true,
                            IsRecurring = true,
                            ItemCode = "MODULE_INVENTORY",
                            Name = "Módulo de Inventario",
                            PricingItemTypeId = new Guid("10000000-0000-0000-0000-000000000002"),
                            SortOrder = 10
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            AnnualPrice = 1500m,
                            Description = "Sistema de gestión de relaciones con clientes",
                            IsActive = true,
                            IsRecurring = true,
                            ItemCode = "MODULE_CRM",
                            Name = "Módulo CRM",
                            PricingItemTypeId = new Guid("10000000-0000-0000-0000-000000000002"),
                            SortOrder = 11
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222223"),
                            AnnualPrice = 1800m,
                            Description = "Sistema contable integrado con reportes financieros",
                            IsActive = true,
                            IsRecurring = true,
                            ItemCode = "MODULE_ACCOUNTING",
                            Name = "Módulo de Contabilidad",
                            PricingItemTypeId = new Guid("10000000-0000-0000-0000-000000000002"),
                            SortOrder = 12
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222224"),
                            AnnualPrice = 1000m,
                            Description = "Sistema de gestión de recursos humanos y nómina",
                            IsActive = true,
                            IsRecurring = true,
                            ItemCode = "MODULE_HR",
                            Name = "Módulo de Recursos Humanos",
                            PricingItemTypeId = new Guid("10000000-0000-0000-0000-000000000002"),
                            SortOrder = 13
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222225"),
                            AnnualPrice = 2000m,
                            Description = "Dashboards y reportes avanzados con Business Intelligence",
                            IsActive = true,
                            IsRecurring = true,
                            ItemCode = "MODULE_ANALYTICS",
                            Name = "Módulo de Analítica Avanzada",
                            PricingItemTypeId = new Guid("10000000-0000-0000-0000-000000000002"),
                            SortOrder = 14
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222226"),
                            AnnualPrice = 2500m,
                            Description = "Plataforma de ventas online integrada",
                            IsActive = true,
                            IsRecurring = true,
                            ItemCode = "MODULE_ECOMMERCE",
                            Name = "Módulo de E-Commerce",
                            PricingItemTypeId = new Guid("10000000-0000-0000-0000-000000000002"),
                            SortOrder = 15
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333331"),
                            AnnualPrice = 120m,
                            Description = "50GB de almacenamiento adicional en la nube",
                            IsActive = true,
                            IsRecurring = true,
                            ItemCode = "STORAGE_50GB",
                            Name = "Almacenamiento 50GB",
                            PricingItemTypeId = new Guid("10000000-0000-0000-0000-000000000003"),
                            SortOrder = 20
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333332"),
                            AnnualPrice = 240m,
                            Description = "100GB de almacenamiento adicional en la nube",
                            IsActive = true,
                            IsRecurring = true,
                            ItemCode = "STORAGE_100GB",
                            Name = "Almacenamiento 100GB",
                            PricingItemTypeId = new Guid("10000000-0000-0000-0000-000000000003"),
                            SortOrder = 21
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            AnnualPrice = 1000m,
                            Description = "500GB de almacenamiento adicional en la nube",
                            IsActive = true,
                            IsRecurring = true,
                            ItemCode = "STORAGE_500GB",
                            Name = "Almacenamiento 500GB",
                            PricingItemTypeId = new Guid("10000000-0000-0000-0000-000000000003"),
                            SortOrder = 22
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444441"),
                            AnnualPrice = 3600m,
                            Description = "Soporte prioritario 24/7 con tiempo de respuesta garantizado de 1 hora",
                            IsActive = true,
                            IsRecurring = true,
                            ItemCode = "SUPPORT_PREMIUM",
                            Name = "Soporte Premium 24/7",
                            PricingItemTypeId = new Guid("10000000-0000-0000-0000-000000000004"),
                            SortOrder = 30
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444442"),
                            AnnualPrice = 6000m,
                            Description = "Account manager dedicado y soporte personalizado",
                            IsActive = true,
                            IsRecurring = true,
                            ItemCode = "SUPPORT_DEDICATED",
                            Name = "Soporte Dedicado",
                            PricingItemTypeId = new Guid("10000000-0000-0000-0000-000000000004"),
                            SortOrder = 31
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555551"),
                            AnnualPrice = 600m,
                            Description = "Límites extendidos de API (100K requests/día) y webhooks ilimitados",
                            IsActive = true,
                            IsRecurring = true,
                            ItemCode = "FEATURE_API_EXTENDED",
                            Name = "API Extendida",
                            PricingItemTypeId = new Guid("10000000-0000-0000-0000-000000000005"),
                            SortOrder = 40
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555552"),
                            AnnualPrice = 2400m,
                            Description = "Personalización completa con tu marca (logo, colores, dominio)",
                            IsActive = true,
                            IsRecurring = true,
                            ItemCode = "FEATURE_WHITE_LABEL",
                            Name = "White Label",
                            PricingItemTypeId = new Guid("10000000-0000-0000-0000-000000000005"),
                            SortOrder = 41
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555553"),
                            AnnualPrice = 1200m,
                            Description = "Autenticación única con SAML 2.0 y OAuth",
                            IsActive = true,
                            IsRecurring = true,
                            ItemCode = "FEATURE_SSO",
                            Name = "Single Sign-On (SSO)",
                            PricingItemTypeId = new Guid("10000000-0000-0000-0000-000000000005"),
                            SortOrder = 42
                        });
                });

            modelBuilder.Entity("TaxVision.Subscription.Domain.Pricing.PricingItemType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("PricingItemTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Code = "USER_LIMIT",
                            Description = "Precio por usuario adicional según tier",
                            IsActive = true,
                            Name = "Límite de Usuarios",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Code = "MODULE",
                            Description = "Módulos adicionales del sistema",
                            IsActive = true,
                            Name = "Módulo",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            Code = "STORAGE",
                            Description = "Almacenamiento adicional en la nube",
                            IsActive = true,
                            Name = "Almacenamiento",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            Code = "SUPPORT",
                            Description = "Planes de soporte adicionales",
                            IsActive = true,
                            Name = "Soporte",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            Code = "FEATURE",
                            Description = "Características y funcionalidades adicionales",
                            IsActive = true,
                            Name = "Característica",
                            SortOrder = 5
                        });
                });

            modelBuilder.Entity("TaxVision.Subscription.Domain.Subscriptions.PendingPlanChange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("AdditionalUsers")
                        .HasColumnType("int");

                    b.Property<DateTime?>("AppliedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("AppliedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsApplied")
                        .HasColumnType("bit");

                    b.Property<string>("Metadata")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("ModulesAffected")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int?>("NewBillingPeriod")
                        .HasColumnType("int");

                    b.Property<Guid?>("NewPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NewPlanName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("NewPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NewRecurringAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("NewRenewDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NewUserLimit")
                        .HasColumnType("int");

                    b.Property<int?>("OldBillingPeriod")
                        .HasColumnType("int");

                    b.Property<Guid?>("OldPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OldPlanName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("OldPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("OldRenewDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("OldUserLimit")
                        .HasColumnType("int");

                    b.Property<decimal>("ProratedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("RemainingDays")
                        .HasColumnType("int");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IsApplied");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("PendingPlanChanges", (string)null);
                });

            modelBuilder.Entity("TaxVision.Subscription.Domain.Subscriptions.RenewalNotificationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Details")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("NotificationDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("NotificationDate");

                    b.HasIndex("SubscriptionId");

                    b.HasIndex("TenantId");

                    b.ToTable("RenewalNotificationLogs", (string)null);
                });

            modelBuilder.Entity("TaxVision.Subscription.Domain.Subscriptions.SeatSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BillingAnchorDay")
                        .HasColumnType("int");

                    b.Property<string>("BillingPeriod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ConfirmedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("InvoiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("PeriodEndUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PeriodStartUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PeriodEndUtc");

                    b.HasIndex("SubscriptionId");

                    b.HasIndex("TenantId", "Status");

                    b.ToTable("SeatSubscriptions");
                });

            modelBuilder.Entity("TaxVision.Subscription.Domain.Subscriptions.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BillingAnchorDay")
                        .HasColumnType("int");

                    b.Property<string>("BillingPeriod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("EnrollmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("IncludedSeats")
                        .HasColumnType("int");

                    b.Property<bool>("IsAutoRenew")
                        .HasColumnType("bit");

                    b.Property<int?>("PendingIncludedSeats")
                        .HasColumnType("int");

                    b.Property<string>("PendingPlanCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("PendingPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PendingPlanName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("PeriodEndUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PeriodStartUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PlanCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("TrialEndsAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .IsUnique();

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("TaxVision.Subscription.Domain.Subscriptions.TenantModule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsIncluded")
                        .HasColumnType("bit");

                    b.Property<Guid>("ModuleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.HasIndex("SubscriptionId");

                    b.HasIndex("SubscriptionId", "ModuleId")
                        .IsUnique();

                    b.ToTable("TenantModules", (string)null);
                });

            modelBuilder.Entity("TaxVision.Subscription.Domain.Billing.Transaction", b =>
                {
                    b.HasOne("TaxVision.Subscription.Domain.Billing.TransactionStatus", "TransactionStatus")
                        .WithMany("Transactions")
                        .HasForeignKey("TransactionStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaxVision.Subscription.Domain.Billing.TransactionType", "TransactionType")
                        .WithMany("Transactions")
                        .HasForeignKey("TransactionTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TransactionStatus");

                    b.Navigation("TransactionType");
                });

            modelBuilder.Entity("TaxVision.Subscription.Domain.Billing.TransactionDetail", b =>
                {
                    b.HasOne("TaxVision.Subscription.Domain.Billing.Transaction", "Transaction")
                        .WithMany("Details")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("TaxVision.Subscription.Domain.Billing.TransactionHistory", b =>
                {
                    b.HasOne("TaxVision.Subscription.Domain.Billing.Transaction", "Transaction")
                        .WithMany("History")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("TaxVision.Subscription.Domain.Modules.PlanModule", b =>
                {
                    b.HasOne("TaxVision.Subscription.Domain.Modules.Module", "Module")
                        .WithMany("PlanModules")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaxVision.Subscription.Domain.Plans.Plan", null)
                        .WithMany("PlanModules")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("TaxVision.Subscription.Domain.Plans.PlanFeature", b =>
                {
                    b.HasOne("TaxVision.Subscription.Domain.Plans.Plan", null)
                        .WithMany("Features")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TaxVision.Subscription.Domain.Pricing.PricingHistory", b =>
                {
                    b.HasOne("TaxVision.Subscription.Domain.Pricing.PricingItem", "PricingItem")
                        .WithMany()
                        .HasForeignKey("PricingItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PricingItem");
                });

            modelBuilder.Entity("TaxVision.Subscription.Domain.Pricing.PricingItem", b =>
                {
                    b.HasOne("TaxVision.Subscription.Domain.Pricing.PricingItemType", "PricingItemType")
                        .WithMany("PricingItems")
                        .HasForeignKey("PricingItemTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PricingItemType");
                });

            modelBuilder.Entity("TaxVision.Subscription.Domain.Subscriptions.PendingPlanChange", b =>
                {
                    b.HasOne("TaxVision.Subscription.Domain.Subscriptions.Subscription", "Subscription")
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("TaxVision.Subscription.Domain.Subscriptions.SeatSubscription", b =>
                {
                    b.HasOne("TaxVision.Subscription.Domain.Subscriptions.Subscription", null)
                        .WithMany("Seats")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("TaxVision.Subscription.Domain.ValueObjects.Money", "PricePerSeat", b1 =>
                        {
                            b1.Property<Guid>("SeatSubscriptionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(19, 4)
                                .HasColumnType("decimal(19,4)")
                                .HasColumnName("PricePerSeat_Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("PricePerSeat_Currency");

                            b1.HasKey("SeatSubscriptionId");

                            b1.ToTable("SeatSubscriptions");

                            b1.WithOwner()
                                .HasForeignKey("SeatSubscriptionId");
                        });

                    b.OwnsOne("TaxVision.Subscription.Domain.ValueObjects.Money", "TotalAmount", b1 =>
                        {
                            b1.Property<Guid>("SeatSubscriptionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(19, 4)
                                .HasColumnType("decimal(19,4)")
                                .HasColumnName("TotalAmount_Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("TotalAmount_Currency");

                            b1.HasKey("SeatSubscriptionId");

                            b1.ToTable("SeatSubscriptions");

                            b1.WithOwner()
                                .HasForeignKey("SeatSubscriptionId");
                        });

                    b.Navigation("PricePerSeat")
                        .IsRequired();

                    b.Navigation("TotalAmount")
                        .IsRequired();
                });

            modelBuilder.Entity("TaxVision.Subscription.Domain.Subscriptions.Subscription", b =>
                {
                    b.OwnsOne("TaxVision.Subscription.Domain.ValueObjects.Money", "CurrentBasePrice", b1 =>
                        {
                            b1.Property<Guid>("SubscriptionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(19, 4)
                                .HasColumnType("decimal(19,4)")
                                .HasColumnName("BasePrice_Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("BasePrice_Currency");

                            b1.HasKey("SubscriptionId");

                            b1.ToTable("Subscriptions");

                            b1.WithOwner()
                                .HasForeignKey("SubscriptionId");
                        });

                    b.OwnsOne("TaxVision.Subscription.Domain.ValueObjects.Money", "CurrentPricePerSeat", b1 =>
                        {
                            b1.Property<Guid>("SubscriptionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(19, 4)
                                .HasColumnType("decimal(19,4)")
                                .HasColumnName("SeatPrice_Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("SeatPrice_Currency");

                            b1.HasKey("SubscriptionId");

                            b1.ToTable("Subscriptions");

                            b1.WithOwner()
                                .HasForeignKey("SubscriptionId");
                        });

                    b.Navigation("CurrentBasePrice")
                        .IsRequired();

                    b.Navigation("CurrentPricePerSeat")
                        .IsRequired();
                });

            modelBuilder.Entity("TaxVision.Subscription.Domain.Subscriptions.TenantModule", b =>
                {
                    b.HasOne("TaxVision.Subscription.Domain.Subscriptions.Subscription", null)
                        .WithMany("TenantModules")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TaxVision.Subscription.Domain.Billing.Transaction", b =>
                {
                    b.Navigation("Details");

                    b.Navigation("History");
                });

            modelBuilder.Entity("TaxVision.Subscription.Domain.Billing.TransactionStatus", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("TaxVision.Subscription.Domain.Billing.TransactionType", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("TaxVision.Subscription.Domain.Modules.Module", b =>
                {
                    b.Navigation("PlanModules");
                });

            modelBuilder.Entity("TaxVision.Subscription.Domain.Plans.Plan", b =>
                {
                    b.Navigation("Features");

                    b.Navigation("PlanModules");
                });

            modelBuilder.Entity("TaxVision.Subscription.Domain.Pricing.PricingItemType", b =>
                {
                    b.Navigation("PricingItems");
                });

            modelBuilder.Entity("TaxVision.Subscription.Domain.Subscriptions.Subscription", b =>
                {
                    b.Navigation("Seats");

                    b.Navigation("TenantModules");
                });
#pragma warning restore 612, 618
        }
    }
}
