// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaxVision.Scribe.Infrastructure.Persistence;

#nullable disable

namespace TaxVision.Scribe.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ScribeDbContext))]
    [Migration("20260717142208_AddEventTemplateMappings")]
    partial class AddEventTemplateMappings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaxVision.Scribe.Domain.EventMappings.EventTemplateMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<string>("EventKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("EventKey");

                    b.Property<string>("Locale")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Locale");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("TemplateKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("TemplateKey");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EventKey", "Enabled");

                    b.HasIndex("Scope", "TenantId", "EventKey", "Locale")
                        .IsUnique();

                    b.ToTable("EventTemplateMappings", (string)null);
                });

            modelBuilder.Entity("TaxVision.Scribe.Domain.Layouts.EmailLayout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("LayoutKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("LayoutKey");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Scope", "TenantId", "LayoutKey")
                        .IsUnique();

                    b.ToTable("EmailLayouts", (string)null);
                });

            modelBuilder.Entity("TaxVision.Scribe.Domain.Layouts.EmailLayoutVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DesignJsonFileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DesignJsonStorageKey")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("EmailLayoutId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HtmlFileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HtmlStorageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("PreviewImageFileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PreviewImageStorageKey")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("PublishedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmailLayoutId", "Status")
                        .IsUnique()
                        .HasFilter("[Status] = 'Published'");

                    b.HasIndex("EmailLayoutId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("EmailLayoutVersions", (string)null);
                });

            modelBuilder.Entity("TaxVision.Scribe.Domain.Templates.EmailTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("TemplateKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("TemplateKey");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Scope", "TenantId", "TemplateKey")
                        .IsUnique();

                    b.ToTable("EmailTemplates", (string)null);
                });

            modelBuilder.Entity("TaxVision.Scribe.Domain.Templates.EmailTemplateVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DesignJsonFileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DesignJsonStorageKey")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("EmailTemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HtmlFileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HtmlStorageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("LayoutId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("LayoutVersionNumber")
                        .HasColumnType("int");

                    b.Property<Guid?>("PreviewImageFileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PreviewImageStorageKey")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("PublishedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("TextFileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TextStorageKey")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmailTemplateId", "Status")
                        .IsUnique()
                        .HasFilter("[Status] = 'Published'");

                    b.HasIndex("EmailTemplateId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("EmailTemplateVersions", (string)null);
                });

            modelBuilder.Entity("TaxVision.Scribe.Domain.Templates.TemplateVariableDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DefaultValue")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("EmailTemplateVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Required")
                        .HasColumnType("bit");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Id");

                    b.HasIndex("EmailTemplateVersionId");

                    b.ToTable("TemplateVariableDefinitions", (string)null);
                });

            modelBuilder.Entity("TaxVision.Scribe.Domain.Layouts.EmailLayoutVersion", b =>
                {
                    b.HasOne("TaxVision.Scribe.Domain.Layouts.EmailLayout", null)
                        .WithMany("Versions")
                        .HasForeignKey("EmailLayoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TaxVision.Scribe.Domain.Templates.EmailTemplateVersion", b =>
                {
                    b.HasOne("TaxVision.Scribe.Domain.Templates.EmailTemplate", null)
                        .WithMany("Versions")
                        .HasForeignKey("EmailTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TaxVision.Scribe.Domain.Templates.TemplateVariableDefinition", b =>
                {
                    b.HasOne("TaxVision.Scribe.Domain.Templates.EmailTemplateVersion", null)
                        .WithMany("VariableDefinitions")
                        .HasForeignKey("EmailTemplateVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TaxVision.Scribe.Domain.Layouts.EmailLayout", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("TaxVision.Scribe.Domain.Templates.EmailTemplate", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("TaxVision.Scribe.Domain.Templates.EmailTemplateVersion", b =>
                {
                    b.Navigation("VariableDefinitions");
                });
#pragma warning restore 612, 618
        }
    }
}
