// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaxVision.Tenant.Infrastructure.Persistence;

#nullable disable

namespace TaxVision.Tenant.Infrastructure.Migrations
{
    [DbContext(typeof(TenantDbContext))]
    [Migration("20260719172648_AddTenantLogoFields")]
    partial class AddTenantLogoFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaxVision.Tenant.Domain.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DefaultTimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LogoContentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("LogoFileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("LogoHeight")
                        .HasColumnType("int");

                    b.Property<long?>("LogoSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LogoUpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LogoWidth")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubDomain")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("SubDomain")
                        .IsUnique();

                    b.ToTable("Tenants", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8f58a521-4c25-4d91-9f4e-7ad5df14c001"),
                            CreatedAtUtc = new DateTime(2026, 6, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultTimeZoneId = "Etc/UTC",
                            Kind = "Platform",
                            Name = "TaxVision Platform",
                            Status = "Active",
                            SubDomain = "platform-internal"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
