// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaxVision.Correspondence.Infrastructure.Persistence;

#nullable disable

namespace TaxVision.Correspondence.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CorrespondenceDbContext))]
    [Migration("20260718035558_AddUnmatchedIncomingEmails")]
    partial class AddUnmatchedIncomingEmails
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaxVision.Correspondence.Domain.Backfill.TenantBackfillState", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("TenantId");

                    b.ToTable("TenantBackfillStates", (string)null);
                });

            modelBuilder.Entity("TaxVision.Correspondence.Domain.Inbox.EmailThread", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ArchivedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FirstMessageAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastMessageAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("MessageCount")
                        .HasColumnType("int");

                    b.Property<string>("ProviderThreadId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ProviderThreadId")
                        .IsUnique()
                        .HasDatabaseName("IX_EmailThreads_TenantId_ProviderThreadId_Unique")
                        .HasFilter("[ProviderThreadId] IS NOT NULL");

                    b.HasIndex("TenantId", "CustomerId", "LastMessageAtUtc")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("IX_EmailThreads_TenantId_CustomerId_LastMessageAtUtc");

                    b.ToTable("EmailThreads", (string)null);
                });

            modelBuilder.Entity("TaxVision.Correspondence.Domain.Inbox.IncomingEmail", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttachmentCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("BodyFetchedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("BodyStatus")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EmailThreadId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("FromDisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("HasAttachments")
                        .HasColumnType("bit");

                    b.Property<string>("InReplyTo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("InternetMessageId")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ProviderCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ProviderMessageId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("References")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Snippet")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "InternetMessageId")
                        .IsUnique()
                        .HasDatabaseName("IX_IncomingEmails_TenantId_InternetMessageId_Unique")
                        .HasFilter("[InternetMessageId] IS NOT NULL");

                    b.HasIndex("TenantId", "CustomerId", "ReceivedAtUtc")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("IX_IncomingEmails_TenantId_CustomerId_ReceivedAtUtc");

                    b.ToTable("IncomingEmails", (string)null);
                });

            modelBuilder.Entity("TaxVision.Correspondence.Domain.Inbox.IncomingEmailAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CloudStorageFileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DownloadStatus")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTime?>("DownloadedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("IncomingEmailId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsInline")
                        .HasColumnType("bit");

                    b.Property<string>("ProviderAttachmentId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DownloadStatus")
                        .HasDatabaseName("IX_IncomingEmailAttachments_DownloadStatus");

                    b.HasIndex("IncomingEmailId");

                    b.ToTable("IncomingEmailAttachments", (string)null);
                });

            modelBuilder.Entity("TaxVision.Correspondence.Domain.Inbox.IncomingEmailRecipient", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("IncomingEmailId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.HasKey("Id");

                    b.HasIndex("IncomingEmailId");

                    b.HasIndex("TenantId", "Address")
                        .HasDatabaseName("IX_IncomingEmailRecipients_TenantId_Address");

                    b.ToTable("IncomingEmailRecipients", (string)null);
                });

            modelBuilder.Entity("TaxVision.Correspondence.Domain.Inbox.UnmatchedIncomingEmail", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("FromAddress")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("ProviderMessageId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAtUtc")
                        .HasDatabaseName("IX_UnmatchedIncomingEmails_ExpiresAtUtc");

                    b.HasIndex("TenantId", "Reason")
                        .HasDatabaseName("IX_UnmatchedIncomingEmails_TenantId_Reason");

                    b.ToTable("UnmatchedIncomingEmails", (string)null);
                });

            modelBuilder.Entity("TaxVision.Correspondence.Domain.Projections.CustomerEmailAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "CustomerId")
                        .HasDatabaseName("IX_CustomerEmailAddresses_TenantId_CustomerId");

                    b.HasIndex("TenantId", "EmailAddress")
                        .IsUnique()
                        .HasDatabaseName("IX_CustomerEmailAddresses_TenantId_EmailAddress_Active")
                        .HasFilter("[DeletedAtUtc] IS NULL");

                    b.ToTable("CustomerEmailAddresses", (string)null);
                });

            modelBuilder.Entity("TaxVision.Correspondence.Domain.Inbox.IncomingEmailAttachment", b =>
                {
                    b.HasOne("TaxVision.Correspondence.Domain.Inbox.IncomingEmail", null)
                        .WithMany("Attachments")
                        .HasForeignKey("IncomingEmailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TaxVision.Correspondence.Domain.Inbox.IncomingEmailRecipient", b =>
                {
                    b.HasOne("TaxVision.Correspondence.Domain.Inbox.IncomingEmail", null)
                        .WithMany("Recipients")
                        .HasForeignKey("IncomingEmailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TaxVision.Correspondence.Domain.Inbox.IncomingEmail", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Recipients");
                });
#pragma warning restore 612, 618
        }
    }
}
