// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaxVision.Signature.Infrastructure.Persistence;

#nullable disable

namespace TaxVision.Signature.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SignatureDbContext))]
    [Migration("20260710005754_AddSignatureRequests")]
    partial class AddSignatureRequests
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaxVision.Signature.Domain.Requests.SignatureField", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Label")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("SignatureRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SignerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SignerId");

                    b.ToTable("SignatureFields", (string)null);
                });

            modelBuilder.Entity("TaxVision.Signature.Domain.Requests.SignatureRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CanceledAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid?>("CertificateFileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("ExpiredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("GenerateCertificate")
                        .HasColumnType("bit");

                    b.Property<Guid>("OriginalFileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("RejectedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("RejectedBySignerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("RequiresConsent")
                        .HasColumnType("bit");

                    b.Property<bool>("RequiresSequentialSigning")
                        .HasColumnType("bit");

                    b.Property<int>("RevocationEpoch")
                        .HasColumnType("int");

                    b.Property<Guid?>("SealedFileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("SentAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("TokenExpirationHours")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "CreatedAtUtc");

                    b.HasIndex("TenantId", "ExpiresAtUtc");

                    b.HasIndex("TenantId", "Status");

                    b.ToTable("SignatureRequests", (string)null);
                });

            modelBuilder.Entity("TaxVision.Signature.Domain.Requests.Signer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClientIp")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<Guid?>("MappedCustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("RejectReason")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("RejectedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SignatureRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("SignedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("SignatureRequestId", "Order")
                        .IsUnique();

                    b.ToTable("Signers", (string)null);
                });

            modelBuilder.Entity("TaxVision.Signature.Domain.Settings.TenantSignatureSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AllowedVerificationChannels")
                        .HasColumnType("int");

                    b.Property<int>("AuditKeyVersion")
                        .HasColumnType("int");

                    b.Property<string>("AuditSecretEncrypted")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("DefaultTokenExpirationHoursValue")
                        .HasColumnType("int");

                    b.Property<int>("DefaultVerificationChannel")
                        .HasColumnType("int");

                    b.Property<bool>("GenerateCertificateByDefault")
                        .HasColumnType("bit");

                    b.Property<bool>("RemindersEnabledByDefault")
                        .HasColumnType("bit");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .IsUnique();

                    b.ToTable("TenantSignatureSettings", (string)null);
                });

            modelBuilder.Entity("TaxVision.Signature.Domain.Requests.SignatureField", b =>
                {
                    b.HasOne("TaxVision.Signature.Domain.Requests.Signer", null)
                        .WithMany("Fields")
                        .HasForeignKey("SignerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("TaxVision.Signature.Domain.Requests.ValueObjects.FieldPosition", "Position", b1 =>
                        {
                            b1.Property<Guid>("SignatureFieldId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<double>("Height")
                                .HasColumnType("float")
                                .HasColumnName("Position_Height");

                            b1.Property<int>("Page")
                                .HasColumnType("int")
                                .HasColumnName("Position_Page");

                            b1.Property<double>("Width")
                                .HasColumnType("float")
                                .HasColumnName("Position_Width");

                            b1.Property<double>("X")
                                .HasColumnType("float")
                                .HasColumnName("Position_X");

                            b1.Property<double>("Y")
                                .HasColumnType("float")
                                .HasColumnName("Position_Y");

                            b1.HasKey("SignatureFieldId");

                            b1.ToTable("SignatureFields");

                            b1.WithOwner()
                                .HasForeignKey("SignatureFieldId");
                        });

                    b.Navigation("Position")
                        .IsRequired();
                });

            modelBuilder.Entity("TaxVision.Signature.Domain.Requests.SignatureRequest", b =>
                {
                    b.OwnsOne("TaxVision.Signature.Domain.Requests.ValueObjects.DocumentHash", "DocumentHashPost", b1 =>
                        {
                            b1.Property<Guid>("SignatureRequestId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("DocumentHashPost");

                            b1.HasKey("SignatureRequestId");

                            b1.ToTable("SignatureRequests");

                            b1.WithOwner()
                                .HasForeignKey("SignatureRequestId");
                        });

                    b.OwnsOne("TaxVision.Signature.Domain.Requests.ValueObjects.DocumentHash", "DocumentHashPre", b1 =>
                        {
                            b1.Property<Guid>("SignatureRequestId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("DocumentHashPre");

                            b1.HasKey("SignatureRequestId");

                            b1.ToTable("SignatureRequests");

                            b1.WithOwner()
                                .HasForeignKey("SignatureRequestId");
                        });

                    b.Navigation("DocumentHashPost");

                    b.Navigation("DocumentHashPre");
                });

            modelBuilder.Entity("TaxVision.Signature.Domain.Requests.Signer", b =>
                {
                    b.HasOne("TaxVision.Signature.Domain.Requests.SignatureRequest", null)
                        .WithMany("Signers")
                        .HasForeignKey("SignatureRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("TaxVision.Signature.Domain.Requests.ValueObjects.SignerEmail", "Email", b1 =>
                        {
                            b1.Property<Guid>("SignerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(320)
                                .HasColumnType("nvarchar(320)")
                                .HasColumnName("Email");

                            b1.HasKey("SignerId");

                            b1.HasIndex("Value");

                            b1.ToTable("Signers");

                            b1.WithOwner()
                                .HasForeignKey("SignerId");
                        });

                    b.OwnsOne("TaxVision.Signature.Domain.Requests.ValueObjects.SignerFullName", "FullName", b1 =>
                        {
                            b1.Property<Guid>("SignerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("FullName");

                            b1.HasKey("SignerId");

                            b1.ToTable("Signers");

                            b1.WithOwner()
                                .HasForeignKey("SignerId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("FullName")
                        .IsRequired();
                });

            modelBuilder.Entity("TaxVision.Signature.Domain.Settings.TenantSignatureSettings", b =>
                {
                    b.OwnsOne("TaxVision.Signature.Domain.Settings.DocumentLimits", "DocumentLimits", b1 =>
                        {
                            b1.Property<Guid>("TenantSignatureSettingsId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<long>("MaxImageBytes")
                                .HasColumnType("bigint")
                                .HasColumnName("Limits_MaxImageBytes");

                            b1.Property<int>("MaxPagesPerDocument")
                                .HasColumnType("int")
                                .HasColumnName("Limits_MaxPagesPerDocument");

                            b1.Property<long>("MaxPdfBytes")
                                .HasColumnType("bigint")
                                .HasColumnName("Limits_MaxPdfBytes");

                            b1.HasKey("TenantSignatureSettingsId");

                            b1.ToTable("TenantSignatureSettings");

                            b1.WithOwner()
                                .HasForeignKey("TenantSignatureSettingsId");
                        });

                    b.OwnsOne("TaxVision.Signature.Domain.Settings.RetentionPolicy", "Retention", b1 =>
                        {
                            b1.Property<Guid>("TenantSignatureSettingsId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("AllowPurge")
                                .HasColumnType("bit")
                                .HasColumnName("Retention_AllowPurge");

                            b1.Property<int>("RetentionYears")
                                .HasColumnType("int")
                                .HasColumnName("Retention_Years");

                            b1.HasKey("TenantSignatureSettingsId");

                            b1.ToTable("TenantSignatureSettings");

                            b1.WithOwner()
                                .HasForeignKey("TenantSignatureSettingsId");
                        });

                    b.Navigation("DocumentLimits")
                        .IsRequired();

                    b.Navigation("Retention")
                        .IsRequired();
                });

            modelBuilder.Entity("TaxVision.Signature.Domain.Requests.SignatureRequest", b =>
                {
                    b.Navigation("Signers");
                });

            modelBuilder.Entity("TaxVision.Signature.Domain.Requests.Signer", b =>
                {
                    b.Navigation("Fields");
                });
#pragma warning restore 612, 618
        }
    }
}
