// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaxVision.PaymentApp.Infrastructure.Persistence;

#nullable disable

namespace TaxVision.PaymentApp.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PaymentAppDbContext))]
    [Migration("20260714143431_AddPaymentMethodExpiryNotice")]
    partial class AddPaymentMethodExpiryNotice
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaxVision.PaymentApp.Domain.Audit.PaymentAuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AfterPayload")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BeforePayload")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CausationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "AggregateType", "AggregateId")
                        .HasDatabaseName("IX_PaymentAuditEntries_TenantId_Aggregate");

                    b.ToTable("PaymentAuditEntries", (string)null);
                });

            modelBuilder.Entity("TaxVision.PaymentApp.Domain.ProviderCustomers.TenantProviderCustomer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("ProviderCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ProviderCode")
                        .IsUnique()
                        .HasDatabaseName("UX_TenantProviderCustomers_TenantId_ProviderCode");

                    b.ToTable("TenantProviderCustomers", (string)null);
                });

            modelBuilder.Entity("TaxVision.PaymentApp.Domain.ProviderCustomers.TenantSavedPaymentMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DetachedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExpMonth")
                        .HasColumnType("int");

                    b.Property<int>("ExpYear")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExpiryNoticeSentAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDetached")
                        .HasColumnType("bit");

                    b.Property<string>("Last4")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("MethodReference")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantProviderCustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ExpYear", "ExpMonth")
                        .HasDatabaseName("IX_TenantSavedPaymentMethods_Expiration")
                        .HasFilter("[IsDetached] = 0");

                    b.HasIndex("TenantProviderCustomerId", "MethodReference")
                        .IsUnique()
                        .HasDatabaseName("UX_TenantSavedPaymentMethods_Customer_MethodReference_Active")
                        .HasFilter("[IsDetached] = 0");

                    b.ToTable("TenantSavedPaymentMethods", (string)null);
                });

            modelBuilder.Entity("TaxVision.PaymentApp.Domain.SaaSPayments.RefundLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ExternalRefundReference")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("RefundedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RequestedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SaaSPaymentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SaaSPaymentId")
                        .HasDatabaseName("IX_RefundLines_SaaSPaymentId");

                    b.ToTable("RefundLines", (string)null);
                });

            modelBuilder.Entity("TaxVision.PaymentApp.Domain.SaaSPayments.SaaSPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ChargedBackAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("IdempotencyKey");

                    b.Property<bool>("IsLegalHeld")
                        .HasColumnType("bit");

                    b.Property<string>("NextActionType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NextActionUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("NextRetryAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PaidAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProviderCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("StatementDescriptor")
                        .IsRequired()
                        .HasMaxLength(22)
                        .HasColumnType("nvarchar(22)")
                        .HasColumnName("StatementDescriptor");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("TargetAggregateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("UX_SaaSPayments_IdempotencyKey");

                    b.HasIndex("NextRetryAtUtc")
                        .HasDatabaseName("IX_SaaSPayments_Status_NextRetry")
                        .HasFilter("[Status] = 'Failed' AND [NextRetryAtUtc] IS NOT NULL");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("IX_SaaSPayments_TenantId_Status");

                    b.ToTable("SaaSPayments", (string)null);
                });

            modelBuilder.Entity("TaxVision.PaymentApp.Domain.SaaSPayments.SaaSPaymentAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("AttemptedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProviderResponseBody")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderResponseCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("SaaSPaymentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SaaSPaymentId")
                        .HasDatabaseName("IX_SaaSPaymentAttempts_SaaSPaymentId");

                    b.ToTable("SaaSPaymentAttempts", (string)null);
                });

            modelBuilder.Entity("TaxVision.PaymentApp.Domain.Tenants.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DefaultTimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("SubDomain")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SubDomain")
                        .IsUnique()
                        .HasDatabaseName("UX_Tenants_SubDomain");

                    b.ToTable("Tenants", (string)null);
                });

            modelBuilder.Entity("TaxVision.PaymentApp.Domain.Webhooks.WebhookEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProcessingError")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ProviderCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ProviderEventId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RawPayload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("RelatedSaaSPaymentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SignatureHeader")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ProviderCode", "ProviderEventId")
                        .IsUnique()
                        .HasDatabaseName("UX_WebhookEvents_ProviderCode_ProviderEventId");

                    b.ToTable("WebhookEvents", (string)null);
                });

            modelBuilder.Entity("TaxVision.PaymentApp.Domain.ProviderCustomers.TenantProviderCustomer", b =>
                {
                    b.OwnsOne("TaxVision.PaymentApp.Domain.ValueObjects.ProviderCustomerReference", "CustomerReference", b1 =>
                        {
                            b1.Property<Guid>("TenantProviderCustomerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Provider")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)")
                                .HasColumnName("CustomerReferenceProvider");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("CustomerReferenceValue");

                            b1.HasKey("TenantProviderCustomerId");

                            b1.ToTable("TenantProviderCustomers");

                            b1.WithOwner()
                                .HasForeignKey("TenantProviderCustomerId");
                        });

                    b.Navigation("CustomerReference")
                        .IsRequired();
                });

            modelBuilder.Entity("TaxVision.PaymentApp.Domain.ProviderCustomers.TenantSavedPaymentMethod", b =>
                {
                    b.HasOne("TaxVision.PaymentApp.Domain.ProviderCustomers.TenantProviderCustomer", null)
                        .WithMany("SavedMethods")
                        .HasForeignKey("TenantProviderCustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TaxVision.PaymentApp.Domain.SaaSPayments.RefundLine", b =>
                {
                    b.HasOne("TaxVision.PaymentApp.Domain.SaaSPayments.SaaSPayment", null)
                        .WithMany("Refunds")
                        .HasForeignKey("SaaSPaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("TaxVision.PaymentApp.Domain.ValueObjects.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("RefundLineId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<long>("AmountCents")
                                .HasColumnType("bigint")
                                .HasColumnName("AmountCents");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("Currency");

                            b1.HasKey("RefundLineId");

                            b1.ToTable("RefundLines");

                            b1.WithOwner()
                                .HasForeignKey("RefundLineId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();
                });

            modelBuilder.Entity("TaxVision.PaymentApp.Domain.SaaSPayments.SaaSPayment", b =>
                {
                    b.OwnsOne("TaxVision.PaymentApp.Domain.ValueObjects.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("SaaSPaymentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<long>("AmountCents")
                                .HasColumnType("bigint")
                                .HasColumnName("AmountCents");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("Currency");

                            b1.HasKey("SaaSPaymentId");

                            b1.ToTable("SaaSPayments");

                            b1.WithOwner()
                                .HasForeignKey("SaaSPaymentId");
                        });

                    b.OwnsOne("TaxVision.PaymentApp.Domain.ValueObjects.ExternalPaymentReference", "ExternalChargeReference", b1 =>
                        {
                            b1.Property<Guid>("SaaSPaymentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Provider")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)")
                                .HasColumnName("ExternalChargeProvider");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("ExternalChargeReference");

                            b1.HasKey("SaaSPaymentId");

                            b1.ToTable("SaaSPayments");

                            b1.WithOwner()
                                .HasForeignKey("SaaSPaymentId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();

                    b.Navigation("ExternalChargeReference");
                });

            modelBuilder.Entity("TaxVision.PaymentApp.Domain.SaaSPayments.SaaSPaymentAttempt", b =>
                {
                    b.HasOne("TaxVision.PaymentApp.Domain.SaaSPayments.SaaSPayment", null)
                        .WithMany("Attempts")
                        .HasForeignKey("SaaSPaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TaxVision.PaymentApp.Domain.ProviderCustomers.TenantProviderCustomer", b =>
                {
                    b.Navigation("SavedMethods");
                });

            modelBuilder.Entity("TaxVision.PaymentApp.Domain.SaaSPayments.SaaSPayment", b =>
                {
                    b.Navigation("Attempts");

                    b.Navigation("Refunds");
                });
#pragma warning restore 612, 618
        }
    }
}
