// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaxVision.Subscription.Infrastructure.Persistence;

#nullable disable

namespace TaxVision.Subscription.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SubscriptionDbContext))]
    [Migration("20260712195914_AddEntitlementsAndAddOns")]
    partial class AddEntitlementsAndAddOns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaxVision.Subscription.Domain.AddOns.AddOnDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AllowMultipleInstances")
                        .HasColumnType("bit");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("_supportedBillingCycles")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("SupportedBillingCycles");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("AddOnDefinitions", (string)null);
                });

            modelBuilder.Entity("TaxVision.Subscription.Domain.AddOns.AddOnEntitlementDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AddOnDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MergeStrategy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("AddOnDefinitionId", "Key")
                        .IsUnique();

                    b.ToTable("AddOnEntitlementDefinitions", (string)null);
                });

            modelBuilder.Entity("TaxVision.Subscription.Domain.AddOns.AddOnFeature", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AddOnDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<string>("FeatureKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AddOnDefinitionId", "FeatureKey")
                        .IsUnique();

                    b.ToTable("AddOnFeatures", (string)null);
                });

            modelBuilder.Entity("TaxVision.Subscription.Domain.AddOns.AddOnPriceTier", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AddOnDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BillingCycle")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("MaxQuantity")
                        .HasColumnType("int");

                    b.Property<int>("MinQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AddOnDefinitionId", "BillingCycle", "MinQuantity")
                        .IsUnique();

                    b.ToTable("AddOnPriceTiers", (string)null);
                });

            modelBuilder.Entity("TaxVision.Subscription.Domain.AddOns.TenantAddOn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AddOnCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("AddOnDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AutoRenew")
                        .HasColumnType("bit");

                    b.Property<string>("BillingCycle")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CurrentPeriodEndUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CurrentPeriodStartUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpiredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("GracePeriodEndsAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NextRenewalAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PurchasedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("SuspendedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("SuspensionReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("NextRenewalAtUtc")
                        .HasDatabaseName("IX_TenantAddOns_NextRenewalAtUtc")
                        .HasFilter("[Status] = 'Active' AND [AutoRenew] = 1");

                    b.HasIndex("TenantId", "Status");

                    b.ToTable("TenantAddOns", (string)null);
                });

            modelBuilder.Entity("TaxVision.Subscription.Domain.Entitlements.TenantEntitlementSnapshot", b =>
                {
                    b.Property<Guid>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AvailableSeatCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("ComputedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PlanCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("PlanVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("RevisionNumber")
                        .HasColumnType("bigint");

                    b.Property<int>("SeatCount")
                        .HasColumnType("int");

                    b.Property<string>("SubscriptionStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("_entries")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EntriesJson");

                    b.HasKey("TenantId");

                    b.ToTable("TenantEntitlementSnapshots", (string)null);
                });

            modelBuilder.Entity("TaxVision.Subscription.Domain.Plans.PlanEntitlementDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DefaultValue")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("PlanVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("PlanVersionId", "Key")
                        .IsUnique();

                    b.ToTable("PlanEntitlementDefinitions", (string)null);
                });

            modelBuilder.Entity("TaxVision.Subscription.Domain.Plans.PlanFeature", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("DefaultEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FeatureKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("PlanVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PlanVersionId", "FeatureKey")
                        .IsUnique();

                    b.ToTable("PlanFeatures", (string)null);
                });

            modelBuilder.Entity("TaxVision.Subscription.Domain.Plans.PlanPriceTier", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BillingCycle")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("MaxQuantity")
                        .HasColumnType("int");

                    b.Property<int>("MinQuantity")
                        .HasColumnType("int");

                    b.Property<Guid>("PlanVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PlanVersionId", "BillingCycle", "MinQuantity")
                        .IsUnique();

                    b.ToTable("PlanPriceTiers", (string)null);
                });

            modelBuilder.Entity("TaxVision.Subscription.Domain.Plans.SubscriptionPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("SubscriptionPlans", (string)null);
                });

            modelBuilder.Entity("TaxVision.Subscription.Domain.Plans.SubscriptionPlanVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EffectiveFromUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EffectiveUntilUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("TrialDaysDefault")
                        .HasColumnType("int");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("int");

                    b.Property<string>("_supportedBillingCycles")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("SupportedBillingCycles");

                    b.HasKey("Id");

                    b.HasIndex("PlanId")
                        .IsUnique()
                        .HasDatabaseName("UX_SubscriptionPlanVersions_PlanId_Published")
                        .HasFilter("[Status] = 'Published'");

                    b.HasIndex("PlanId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("SubscriptionPlanVersions", (string)null);
                });

            modelBuilder.Entity("TaxVision.Subscription.Domain.Seats.SubscriptionSeat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AutoRenew")
                        .HasColumnType("bit");

                    b.Property<string>("BillingCycle")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CurrentAssignmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CurrentPeriodEndUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CurrentPeriodStartUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CurrentUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ExpiredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("GracePeriodEndsAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NextRenewalAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PurchasedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("SourceReferenceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("SuspendedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("SuspensionReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CurrentUserId")
                        .HasDatabaseName("IX_SubscriptionSeats_CurrentUserId")
                        .HasFilter("[CurrentUserId] IS NOT NULL");

                    b.HasIndex("NextRenewalAtUtc")
                        .HasDatabaseName("IX_SubscriptionSeats_NextRenewalAtUtc")
                        .HasFilter("[Status] IN ('Active','PastDue') AND [AutoRenew] = 1");

                    b.HasIndex("TenantId", "Status");

                    b.ToTable("SubscriptionSeats", (string)null);
                });

            modelBuilder.Entity("TaxVision.Subscription.Domain.Seats.SubscriptionSeatAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("AssignedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReleaseReason")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("ReleasedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ReleasedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SeatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SeatId")
                        .IsUnique()
                        .HasDatabaseName("UX_SubscriptionSeatAssignments_SeatId_Active")
                        .HasFilter("[ReleasedAtUtc] IS NULL");

                    b.HasIndex("UserId", "TenantId")
                        .HasDatabaseName("IX_SubscriptionSeatAssignments_UserId_TenantId");

                    b.ToTable("SubscriptionSeatAssignments", (string)null);
                });

            modelBuilder.Entity("TaxVision.Subscription.Domain.Settings.SubscriptionTenantSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AllowAddons")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowAdminSeatAssignment")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowAutoRenewSeats")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowAutoRenewTenantSubscription")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowSeatReassignment")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowSeatSelfAssignment")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowTrial")
                        .HasColumnType("bit");

                    b.Property<string>("AutoRenewCascadeMode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DefaultSeatRenewalDays")
                        .HasColumnType("int");

                    b.Property<int?>("MaxSeatsAllowed")
                        .HasColumnType("int");

                    b.Property<int>("MinSeatsRequired")
                        .HasColumnType("int");

                    b.Property<int>("NotifyAfterFailedRenewalDays")
                        .HasColumnType("int");

                    b.Property<bool>("PauseSeatRenewalsWhenBaseSuspended")
                        .HasColumnType("bit");

                    b.Property<string>("PlanChangeEffective")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("SeatGracePeriod")
                        .HasColumnType("int")
                        .HasColumnName("SeatGraceDays");

                    b.Property<int>("SeatReassignmentCooldownDays")
                        .HasColumnType("int");

                    b.Property<bool>("SuspendTenantWhenBaseSubscriptionExpired")
                        .HasColumnType("bit");

                    b.Property<bool>("SuspendUserWhenSeatExpired")
                        .HasColumnType("bit");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TenantSubscriptionGracePeriod")
                        .HasColumnType("int")
                        .HasColumnName("TenantSubscriptionGraceDays");

                    b.Property<int>("TrialDays")
                        .HasColumnType("int")
                        .HasColumnName("TrialDays");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("_notifyBeforeRenewalDays")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("NotifyBeforeRenewalDays");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .IsUnique();

                    b.ToTable("SubscriptionTenantSettings", (string)null);
                });

            modelBuilder.Entity("TaxVision.Subscription.Domain.Subscriptions.TenantSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BillingCycle")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CurrentPeriodEndUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CurrentPeriodStartUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpiredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("GracePeriodEndsAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NextRenewalAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PlanCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlanVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("SuspendedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("SuspensionReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("TrialEndsAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("NextRenewalAtUtc")
                        .HasDatabaseName("IX_TenantSubscriptions_NextRenewalAtUtc")
                        .HasFilter("[Status] = 'Active'");

                    b.HasIndex("PlanId");

                    b.HasIndex("PlanVersionId");

                    b.HasIndex("TenantId")
                        .IsUnique()
                        .HasDatabaseName("UX_TenantSubscriptions_TenantId_Active")
                        .HasFilter("[Status] <> 'Cancelled' AND [Status] <> 'Expired'");

                    b.ToTable("TenantSubscriptions", (string)null);
                });

            modelBuilder.Entity("TaxVision.Subscription.Domain.AddOns.AddOnEntitlementDefinition", b =>
                {
                    b.HasOne("TaxVision.Subscription.Domain.AddOns.AddOnDefinition", null)
                        .WithMany("Entitlements")
                        .HasForeignKey("AddOnDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TaxVision.Subscription.Domain.AddOns.AddOnFeature", b =>
                {
                    b.HasOne("TaxVision.Subscription.Domain.AddOns.AddOnDefinition", null)
                        .WithMany("Features")
                        .HasForeignKey("AddOnDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TaxVision.Subscription.Domain.AddOns.AddOnPriceTier", b =>
                {
                    b.HasOne("TaxVision.Subscription.Domain.AddOns.AddOnDefinition", null)
                        .WithMany("PriceTiers")
                        .HasForeignKey("AddOnDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("TaxVision.Subscription.Domain.ValueObjects.Money", "UnitAmount", b1 =>
                        {
                            b1.Property<Guid>("AddOnPriceTierId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 4)
                                .HasColumnType("decimal(18,4)")
                                .HasColumnName("UnitAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("Currency");

                            b1.HasKey("AddOnPriceTierId");

                            b1.ToTable("AddOnPriceTiers");

                            b1.WithOwner()
                                .HasForeignKey("AddOnPriceTierId");
                        });

                    b.Navigation("UnitAmount")
                        .IsRequired();
                });

            modelBuilder.Entity("TaxVision.Subscription.Domain.AddOns.TenantAddOn", b =>
                {
                    b.OwnsOne("TaxVision.Subscription.Domain.ValueObjects.Money", "UnitPrice", b1 =>
                        {
                            b1.Property<Guid>("TenantAddOnId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 4)
                                .HasColumnType("decimal(18,4)")
                                .HasColumnName("UnitPriceAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("UnitPriceCurrency");

                            b1.HasKey("TenantAddOnId");

                            b1.ToTable("TenantAddOns");

                            b1.WithOwner()
                                .HasForeignKey("TenantAddOnId");
                        });

                    b.Navigation("UnitPrice")
                        .IsRequired();
                });

            modelBuilder.Entity("TaxVision.Subscription.Domain.Plans.PlanEntitlementDefinition", b =>
                {
                    b.HasOne("TaxVision.Subscription.Domain.Plans.SubscriptionPlanVersion", null)
                        .WithMany("Entitlements")
                        .HasForeignKey("PlanVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TaxVision.Subscription.Domain.Plans.PlanFeature", b =>
                {
                    b.HasOne("TaxVision.Subscription.Domain.Plans.SubscriptionPlanVersion", null)
                        .WithMany("Features")
                        .HasForeignKey("PlanVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TaxVision.Subscription.Domain.Plans.PlanPriceTier", b =>
                {
                    b.HasOne("TaxVision.Subscription.Domain.Plans.SubscriptionPlanVersion", null)
                        .WithMany("PriceTiers")
                        .HasForeignKey("PlanVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("TaxVision.Subscription.Domain.ValueObjects.Money", "UnitAmount", b1 =>
                        {
                            b1.Property<Guid>("PlanPriceTierId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 4)
                                .HasColumnType("decimal(18,4)")
                                .HasColumnName("UnitAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("Currency");

                            b1.HasKey("PlanPriceTierId");

                            b1.ToTable("PlanPriceTiers");

                            b1.WithOwner()
                                .HasForeignKey("PlanPriceTierId");
                        });

                    b.Navigation("UnitAmount")
                        .IsRequired();
                });

            modelBuilder.Entity("TaxVision.Subscription.Domain.Plans.SubscriptionPlanVersion", b =>
                {
                    b.HasOne("TaxVision.Subscription.Domain.Plans.SubscriptionPlan", null)
                        .WithMany("Versions")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TaxVision.Subscription.Domain.Seats.SubscriptionSeat", b =>
                {
                    b.OwnsOne("TaxVision.Subscription.Domain.ValueObjects.Money", "UnitPrice", b1 =>
                        {
                            b1.Property<Guid>("SubscriptionSeatId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 4)
                                .HasColumnType("decimal(18,4)")
                                .HasColumnName("UnitPriceAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("UnitPriceCurrency");

                            b1.HasKey("SubscriptionSeatId");

                            b1.ToTable("SubscriptionSeats");

                            b1.WithOwner()
                                .HasForeignKey("SubscriptionSeatId");
                        });

                    b.Navigation("UnitPrice")
                        .IsRequired();
                });

            modelBuilder.Entity("TaxVision.Subscription.Domain.Seats.SubscriptionSeatAssignment", b =>
                {
                    b.HasOne("TaxVision.Subscription.Domain.Seats.SubscriptionSeat", null)
                        .WithMany("Assignments")
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TaxVision.Subscription.Domain.Subscriptions.TenantSubscription", b =>
                {
                    b.HasOne("TaxVision.Subscription.Domain.Plans.SubscriptionPlan", null)
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaxVision.Subscription.Domain.Plans.SubscriptionPlanVersion", null)
                        .WithMany()
                        .HasForeignKey("PlanVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TaxVision.Subscription.Domain.AddOns.AddOnDefinition", b =>
                {
                    b.Navigation("Entitlements");

                    b.Navigation("Features");

                    b.Navigation("PriceTiers");
                });

            modelBuilder.Entity("TaxVision.Subscription.Domain.Plans.SubscriptionPlan", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("TaxVision.Subscription.Domain.Plans.SubscriptionPlanVersion", b =>
                {
                    b.Navigation("Entitlements");

                    b.Navigation("Features");

                    b.Navigation("PriceTiers");
                });

            modelBuilder.Entity("TaxVision.Subscription.Domain.Seats.SubscriptionSeat", b =>
                {
                    b.Navigation("Assignments");
                });
#pragma warning restore 612, 618
        }
    }
}
