// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaxVision.Subscription.Infrastructure.Persistence;

#nullable disable

namespace TaxVision.Subscription.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SubscriptionDbContext))]
    partial class SubscriptionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaxVision.Subscription.Domain.Plans.Plan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("EnabledModulesJson")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MaxPendingInvitations")
                        .HasColumnType("int");

                    b.Property<int>("MaxUsers")
                        .HasColumnType("int");

                    b.Property<decimal>("MonthlyPriceUsd")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<long>("StorageQuotaBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Plans", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1000000-0000-0000-0000-000000000001"),
                            Code = "starter",
                            Description = "Para oficinas que están empezando: 3 usuarios, clientes, firmas y documentos.",
                            EnabledModulesJson = "[\"customers\",\"signatures\",\"documents\",\"planner\"]",
                            IsActive = true,
                            MaxPendingInvitations = 5,
                            MaxUsers = 3,
                            MonthlyPriceUsd = 49m,
                            Name = "Starter",
                            SortOrder = 1,
                            StorageQuotaBytes = 10737418240L
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-0000-0000-000000000002"),
                            Code = "pro",
                            Description = "Para oficinas en crecimiento: 10 usuarios, correo, comunicación y campañas.",
                            EnabledModulesJson = "[\"customers\",\"signatures\",\"documents\",\"planner\",\"email\",\"comms\",\"campaigns\",\"reports\"]",
                            IsActive = true,
                            MaxPendingInvitations = 15,
                            MaxUsers = 10,
                            MonthlyPriceUsd = 129m,
                            Name = "Pro",
                            SortOrder = 2,
                            StorageQuotaBytes = 53687091200L
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-0000-0000-000000000003"),
                            Code = "enterprise",
                            Description = "Para multiservices con equipos grandes: 25 usuarios y todos los módulos.",
                            EnabledModulesJson = "[\"customers\",\"signatures\",\"documents\",\"planner\",\"email\",\"comms\",\"campaigns\",\"reports\",\"marketing\",\"builder\",\"irs\",\"miles\"]",
                            IsActive = true,
                            MaxPendingInvitations = 40,
                            MaxUsers = 25,
                            MonthlyPriceUsd = 299m,
                            Name = "Enterprise",
                            SortOrder = 3,
                            StorageQuotaBytes = 214748364800L
                        });
                });

            modelBuilder.Entity("TaxVision.Subscription.Domain.Subscriptions.TenantSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CurrentPeriodEndUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CurrentPeriodStartUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExtraSeats")
                        .HasColumnType("int");

                    b.Property<string>("PlanCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SuspensionReason")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("TrialEndsAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.HasIndex("Status");

                    b.HasIndex("TenantId")
                        .IsUnique();

                    b.ToTable("Subscriptions", (string)null);
                });

            modelBuilder.Entity("TaxVision.Subscription.Domain.Subscriptions.TenantSubscription", b =>
                {
                    b.HasOne("TaxVision.Subscription.Domain.Plans.Plan", null)
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
