// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaxVision.PaymentClient.Infrastructure.Persistence;

#nullable disable

namespace TaxVision.PaymentClient.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PaymentClientDbContext))]
    partial class PaymentClientDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaxVision.PaymentClient.Domain.Audit.PaymentAuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AfterPayload")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BeforePayload")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CausationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "AggregateType", "AggregateId")
                        .HasDatabaseName("IX_PaymentAuditEntries_TenantId_Aggregate");

                    b.ToTable("PaymentAuditEntries", (string)null);
                });

            modelBuilder.Entity("TaxVision.PaymentClient.Domain.Connect.TenantConnectAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("CanCharge")
                        .HasColumnType("bit");

                    b.Property<bool>("CanReceivePayouts")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("OnboardingStep")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ProviderCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("RequirementsCurrentlyDue")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("RequirementsCurrentlyDue");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("StripeConnectAccountId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("StripeConnectAccountId");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("StripeConnectAccountId")
                        .IsUnique()
                        .HasDatabaseName("UX_TenantConnectAccounts_StripeConnectAccountId");

                    b.HasIndex("TenantId", "ProviderCode")
                        .IsUnique()
                        .HasDatabaseName("UX_TenantConnectAccounts_TenantId_ProviderCode");

                    b.ToTable("TenantConnectAccounts", (string)null);
                });

            modelBuilder.Entity("TaxVision.PaymentClient.Domain.PaymentLinks.PaymentLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("FailedRedemptionAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<Guid?>("RelatedTenantPaymentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid?>("TaxpayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("Token");

                    b.Property<DateTime?>("UsedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAtUtc")
                        .HasDatabaseName("IX_PaymentLinks_Status_ExpiresAtUtc")
                        .HasFilter("[Status] = 'Active'");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("UX_PaymentLinks_Token");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("IX_PaymentLinks_TenantId_Status");

                    b.ToTable("PaymentLinks", (string)null);
                });

            modelBuilder.Entity("TaxVision.PaymentClient.Domain.Payouts.PayoutSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Anchor")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("TenantConnectAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantConnectAccountId")
                        .IsUnique()
                        .HasDatabaseName("UX_PayoutSchedules_TenantConnectAccountId");

                    b.ToTable("PayoutSchedules", (string)null);
                });

            modelBuilder.Entity("TaxVision.PaymentClient.Domain.Payouts.PayoutScheduleItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PayoutScheduleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProviderPayoutReference")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PayoutScheduleId", "ProviderPayoutReference")
                        .IsUnique()
                        .HasDatabaseName("UX_PayoutScheduleItems_ScheduleId_ProviderReference");

                    b.ToTable("PayoutScheduleItems", (string)null);
                });

            modelBuilder.Entity("TaxVision.PaymentClient.Domain.Permissions.RolePermissionsProjection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PermissionCodesJson")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("PermissionsVersion")
                        .HasColumnType("int");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("RolePermissionsProjections", (string)null);
                });

            modelBuilder.Entity("TaxVision.PaymentClient.Domain.Permissions.UserPermissionsProjection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PermissionCodesJson")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("PermissionsVersion")
                        .HasColumnType("int");

                    b.Property<string>("RoleIdsJson")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "IsActive");

                    b.HasIndex("TenantId", "UserId")
                        .IsUnique();

                    b.ToTable("UserPermissionsProjections", (string)null);
                });

            modelBuilder.Entity("TaxVision.PaymentClient.Domain.Recurring.RecurringPaymentExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExecutedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProviderResponse")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("RecurringScheduleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Succeeded")
                        .HasColumnType("bit");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantRecurringPaymentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RecurringScheduleId")
                        .HasDatabaseName("IX_RecurringPaymentExecutions_RecurringScheduleId");

                    b.HasIndex("TenantRecurringPaymentId");

                    b.ToTable("RecurringPaymentExecutions", (string)null);
                });

            modelBuilder.Entity("TaxVision.PaymentClient.Domain.Recurring.RecurringSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("NextRetryAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProviderResponse")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TenantPaymentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantRecurringPaymentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantRecurringPaymentId");

                    b.HasIndex("Status", "NextRetryAtUtc")
                        .HasDatabaseName("IX_RecurringSchedules_Status_NextRetryAtUtc");

                    b.HasIndex("Status", "ScheduledDate")
                        .HasDatabaseName("IX_RecurringSchedules_Status_ScheduledDate");

                    b.ToTable("RecurringSchedules", (string)null);
                });

            modelBuilder.Entity("TaxVision.PaymentClient.Domain.Recurring.TenantRecurringPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BillingCycle")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("CustomIntervalDays")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExecutionCount")
                        .HasColumnType("int");

                    b.Property<int>("FailureCount")
                        .HasColumnType("int");

                    b.Property<int?>("MaxExecutions")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NextExecutionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethodReference")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long?>("PlatformFeeAmountCents")
                        .HasColumnType("bigint");

                    b.Property<string>("PlatformFeeReference")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ProviderCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("TaxpayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("IX_TenantRecurringPayments_TenantId_Status");

                    b.HasIndex("TenantId", "TaxpayerId")
                        .HasDatabaseName("IX_TenantRecurringPayments_TenantId_TaxpayerId");

                    b.ToTable("TenantRecurringPayments", (string)null);
                });

            modelBuilder.Entity("TaxVision.PaymentClient.Domain.TenantPaymentConfigs.TenantPaymentConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ProviderCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PublishableKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SecretKeyEncrypted")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SecretKeyEncrypted");

                    b.Property<DateTime?>("SettledAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("StatementDescriptor")
                        .IsRequired()
                        .HasMaxLength(22)
                        .HasColumnType("nvarchar(22)")
                        .HasColumnName("StatementDescriptor");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WebhookSecretEncrypted")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("WebhookSecretEncrypted");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ProviderCode")
                        .IsUnique()
                        .HasDatabaseName("UX_TenantPaymentConfigs_TenantId_ProviderCode");

                    b.ToTable("TenantPaymentConfigs", (string)null);
                });

            modelBuilder.Entity("TaxVision.PaymentClient.Domain.TenantPaymentConfigs.TenantWebhookEndpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("SigningSecret")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SigningSecretEncrypted");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantPaymentConfigId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("TenantPaymentConfigId")
                        .HasDatabaseName("IX_TenantWebhookEndpoints_TenantPaymentConfigId");

                    b.ToTable("TenantWebhookEndpoints", (string)null);
                });

            modelBuilder.Entity("TaxVision.PaymentClient.Domain.TenantPayments.RefundLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ExternalRefundReference")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("RefundedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RequestedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantPaymentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantPaymentId")
                        .HasDatabaseName("IX_RefundLines_TenantPaymentId");

                    b.ToTable("RefundLines", (string)null);
                });

            modelBuilder.Entity("TaxVision.PaymentClient.Domain.TenantPayments.TenantPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ChargedBackAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("IdempotencyKey");

                    b.Property<bool>("IsLegalHeld")
                        .HasColumnType("bit");

                    b.Property<string>("NextActionType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NextActionUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("NextRetryAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PaidAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProviderChargeReferenceOnConnect")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ProviderChargeReferenceOnConnect");

                    b.Property<string>("ProviderCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("StatementDescriptor")
                        .IsRequired()
                        .HasMaxLength(22)
                        .HasColumnType("nvarchar(22)")
                        .HasColumnName("StatementDescriptor");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid?>("TaxpayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("NextRetryAtUtc")
                        .HasDatabaseName("IX_TenantPayments_Status_NextRetry")
                        .HasFilter("[Status] = 'Failed' AND [NextRetryAtUtc] IS NOT NULL");

                    b.HasIndex("TenantId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("UX_TenantPayments_TenantId_IdempotencyKey");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("IX_TenantPayments_TenantId_Status");

                    b.ToTable("TenantPayments", (string)null);
                });

            modelBuilder.Entity("TaxVision.PaymentClient.Domain.TenantPayments.TenantPaymentAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("AttemptedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProviderResponseBody")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderResponseCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantPaymentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantPaymentId")
                        .HasDatabaseName("IX_TenantPaymentAttempts_TenantPaymentId");

                    b.ToTable("TenantPaymentAttempts", (string)null);
                });

            modelBuilder.Entity("TaxVision.PaymentClient.Domain.Tenants.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DefaultTimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("SubDomain")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SubDomain")
                        .IsUnique()
                        .HasDatabaseName("UX_Tenants_SubDomain");

                    b.ToTable("Tenants", (string)null);
                });

            modelBuilder.Entity("TaxVision.PaymentClient.Domain.Webhooks.WebhookEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProcessingError")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ProviderCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ProviderEventId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RawPayload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("RelatedTenantPaymentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SignatureHeader")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ProviderCode", "ProviderEventId")
                        .IsUnique()
                        .HasDatabaseName("UX_WebhookEvents_TenantId_ProviderCode_ProviderEventId");

                    b.ToTable("WebhookEvents", (string)null);
                });

            modelBuilder.Entity("TaxVision.PaymentClient.Domain.PaymentLinks.PaymentLink", b =>
                {
                    b.OwnsOne("TaxVision.PaymentClient.Domain.ValueObjects.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("PaymentLinkId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<long>("AmountCents")
                                .HasColumnType("bigint")
                                .HasColumnName("AmountCents");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("Currency");

                            b1.HasKey("PaymentLinkId");

                            b1.ToTable("PaymentLinks");

                            b1.WithOwner()
                                .HasForeignKey("PaymentLinkId");
                        });

                    b.OwnsOne("TaxVision.PaymentClient.Domain.ValueObjects.PaymentPurpose", "Purpose", b1 =>
                        {
                            b1.Property<Guid>("PaymentLinkId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("ExternalReferenceId")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("PurposeExternalReferenceId");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)")
                                .HasColumnName("PurposeKind");

                            b1.HasKey("PaymentLinkId");

                            b1.ToTable("PaymentLinks");

                            b1.WithOwner()
                                .HasForeignKey("PaymentLinkId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();

                    b.Navigation("Purpose")
                        .IsRequired();
                });

            modelBuilder.Entity("TaxVision.PaymentClient.Domain.Payouts.PayoutScheduleItem", b =>
                {
                    b.HasOne("TaxVision.PaymentClient.Domain.Payouts.PayoutSchedule", null)
                        .WithMany("Items")
                        .HasForeignKey("PayoutScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("TaxVision.PaymentClient.Domain.ValueObjects.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("PayoutScheduleItemId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<long>("AmountCents")
                                .HasColumnType("bigint")
                                .HasColumnName("AmountCents");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("Currency");

                            b1.HasKey("PayoutScheduleItemId");

                            b1.ToTable("PayoutScheduleItems");

                            b1.WithOwner()
                                .HasForeignKey("PayoutScheduleItemId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();
                });

            modelBuilder.Entity("TaxVision.PaymentClient.Domain.Recurring.RecurringPaymentExecution", b =>
                {
                    b.HasOne("TaxVision.PaymentClient.Domain.Recurring.TenantRecurringPayment", null)
                        .WithMany("Executions")
                        .HasForeignKey("TenantRecurringPaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("TaxVision.PaymentClient.Domain.ValueObjects.Money", "AmountCharged", b1 =>
                        {
                            b1.Property<Guid>("RecurringPaymentExecutionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<long>("AmountCents")
                                .HasColumnType("bigint")
                                .HasColumnName("AmountCents");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("Currency");

                            b1.HasKey("RecurringPaymentExecutionId");

                            b1.ToTable("RecurringPaymentExecutions");

                            b1.WithOwner()
                                .HasForeignKey("RecurringPaymentExecutionId");
                        });

                    b.Navigation("AmountCharged")
                        .IsRequired();
                });

            modelBuilder.Entity("TaxVision.PaymentClient.Domain.Recurring.RecurringSchedule", b =>
                {
                    b.HasOne("TaxVision.PaymentClient.Domain.Recurring.TenantRecurringPayment", null)
                        .WithMany("Schedules")
                        .HasForeignKey("TenantRecurringPaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("TaxVision.PaymentClient.Domain.ValueObjects.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("RecurringScheduleId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<long>("AmountCents")
                                .HasColumnType("bigint")
                                .HasColumnName("AmountCents");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("Currency");

                            b1.HasKey("RecurringScheduleId");

                            b1.ToTable("RecurringSchedules");

                            b1.WithOwner()
                                .HasForeignKey("RecurringScheduleId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();
                });

            modelBuilder.Entity("TaxVision.PaymentClient.Domain.Recurring.TenantRecurringPayment", b =>
                {
                    b.OwnsOne("TaxVision.PaymentClient.Domain.Recurring.RetryPolicy", "RetryPolicy", b1 =>
                        {
                            b1.Property<Guid>("TenantRecurringPaymentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Backoffs")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("RetryBackoffs");

                            b1.Property<int>("MaxFailures")
                                .HasColumnType("int")
                                .HasColumnName("RetryMaxFailures");

                            b1.HasKey("TenantRecurringPaymentId");

                            b1.ToTable("TenantRecurringPayments");

                            b1.WithOwner()
                                .HasForeignKey("TenantRecurringPaymentId");
                        });

                    b.OwnsOne("TaxVision.PaymentClient.Domain.ValueObjects.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("TenantRecurringPaymentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<long>("AmountCents")
                                .HasColumnType("bigint")
                                .HasColumnName("AmountCents");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("Currency");

                            b1.HasKey("TenantRecurringPaymentId");

                            b1.ToTable("TenantRecurringPayments");

                            b1.WithOwner()
                                .HasForeignKey("TenantRecurringPaymentId");
                        });

                    b.OwnsOne("TaxVision.PaymentClient.Domain.ValueObjects.PaymentPurpose", "Purpose", b1 =>
                        {
                            b1.Property<Guid>("TenantRecurringPaymentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("ExternalReferenceId")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("PurposeExternalReferenceId");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)")
                                .HasColumnName("PurposeKind");

                            b1.HasKey("TenantRecurringPaymentId");

                            b1.ToTable("TenantRecurringPayments");

                            b1.WithOwner()
                                .HasForeignKey("TenantRecurringPaymentId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();

                    b.Navigation("Purpose")
                        .IsRequired();

                    b.Navigation("RetryPolicy")
                        .IsRequired();
                });

            modelBuilder.Entity("TaxVision.PaymentClient.Domain.TenantPaymentConfigs.TenantWebhookEndpoint", b =>
                {
                    b.HasOne("TaxVision.PaymentClient.Domain.TenantPaymentConfigs.TenantPaymentConfig", null)
                        .WithMany("WebhookEndpoints")
                        .HasForeignKey("TenantPaymentConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TaxVision.PaymentClient.Domain.TenantPayments.RefundLine", b =>
                {
                    b.HasOne("TaxVision.PaymentClient.Domain.TenantPayments.TenantPayment", null)
                        .WithMany("Refunds")
                        .HasForeignKey("TenantPaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("TaxVision.PaymentClient.Domain.ValueObjects.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("RefundLineId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<long>("AmountCents")
                                .HasColumnType("bigint")
                                .HasColumnName("AmountCents");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("Currency");

                            b1.HasKey("RefundLineId");

                            b1.ToTable("RefundLines");

                            b1.WithOwner()
                                .HasForeignKey("RefundLineId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();
                });

            modelBuilder.Entity("TaxVision.PaymentClient.Domain.TenantPayments.TenantPayment", b =>
                {
                    b.OwnsOne("TaxVision.PaymentClient.Domain.ValueObjects.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("TenantPaymentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<long>("AmountCents")
                                .HasColumnType("bigint")
                                .HasColumnName("AmountCents");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("Currency");

                            b1.HasKey("TenantPaymentId");

                            b1.ToTable("TenantPayments");

                            b1.WithOwner()
                                .HasForeignKey("TenantPaymentId");
                        });

                    b.OwnsOne("TaxVision.PaymentClient.Domain.ValueObjects.PaymentPurpose", "Purpose", b1 =>
                        {
                            b1.Property<Guid>("TenantPaymentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("ExternalReferenceId")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("PurposeExternalReferenceId");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)")
                                .HasColumnName("PurposeKind");

                            b1.HasKey("TenantPaymentId");

                            b1.ToTable("TenantPayments");

                            b1.WithOwner()
                                .HasForeignKey("TenantPaymentId");
                        });

                    b.OwnsOne("TaxVision.PaymentClient.Domain.ValueObjects.ExternalPaymentReference", "ExternalChargeReference", b1 =>
                        {
                            b1.Property<Guid>("TenantPaymentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Provider")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)")
                                .HasColumnName("ExternalChargeProvider");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("ExternalChargeReference");

                            b1.HasKey("TenantPaymentId");

                            b1.ToTable("TenantPayments");

                            b1.WithOwner()
                                .HasForeignKey("TenantPaymentId");
                        });

                    b.OwnsOne("TaxVision.PaymentClient.Domain.ValueObjects.SplitPaymentBreakdown", "SplitPayment", b1 =>
                        {
                            b1.Property<Guid>("TenantPaymentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<long>("PlatformFeeAmountCents")
                                .HasColumnType("bigint")
                                .HasColumnName("PlatformFeeAmountCents");

                            b1.Property<string>("PlatformFeeReference")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("PlatformFeeReference");

                            b1.Property<long>("TenantAmountCents")
                                .HasColumnType("bigint")
                                .HasColumnName("TenantAmountCents");

                            b1.HasKey("TenantPaymentId");

                            b1.ToTable("TenantPayments");

                            b1.WithOwner()
                                .HasForeignKey("TenantPaymentId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();

                    b.Navigation("ExternalChargeReference");

                    b.Navigation("Purpose")
                        .IsRequired();

                    b.Navigation("SplitPayment");
                });

            modelBuilder.Entity("TaxVision.PaymentClient.Domain.TenantPayments.TenantPaymentAttempt", b =>
                {
                    b.HasOne("TaxVision.PaymentClient.Domain.TenantPayments.TenantPayment", null)
                        .WithMany("Attempts")
                        .HasForeignKey("TenantPaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TaxVision.PaymentClient.Domain.Payouts.PayoutSchedule", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("TaxVision.PaymentClient.Domain.Recurring.TenantRecurringPayment", b =>
                {
                    b.Navigation("Executions");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("TaxVision.PaymentClient.Domain.TenantPaymentConfigs.TenantPaymentConfig", b =>
                {
                    b.Navigation("WebhookEndpoints");
                });

            modelBuilder.Entity("TaxVision.PaymentClient.Domain.TenantPayments.TenantPayment", b =>
                {
                    b.Navigation("Attempts");

                    b.Navigation("Refunds");
                });
#pragma warning restore 612, 618
        }
    }
}
