// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaxVision.Reminder.Infrastructure.Persistence;

#nullable disable

namespace TaxVision.Reminder.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ReminderDbContext))]
    [Migration("20260811234418_AddReminders")]
    partial class AddReminders
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaxVision.Reminder.Domain.Reminders.Reminder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FiredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("RequestKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("ResolvedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SnoozeCount")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "RequestKey")
                        .IsUnique()
                        .HasDatabaseName("UX_Reminders_TenantId_RequestKey");

                    b.ToTable("Reminders", (string)null);
                });

            modelBuilder.Entity("TaxVision.Reminder.Domain.Reminders.Reminder", b =>
                {
                    b.OwnsOne("TaxVision.Reminder.Domain.ValueObjects.ReminderSchedule", "Schedule", b1 =>
                        {
                            b1.Property<Guid>("ReminderId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime?>("AnchorAtUtc")
                                .HasColumnType("datetime2")
                                .HasColumnName("AnchorAtUtc");

                            b1.Property<DateTime>("FireAtUtc")
                                .HasColumnType("datetime2")
                                .HasColumnName("FireAtUtc");

                            b1.Property<int?>("LeadMinutes")
                                .HasColumnType("int")
                                .HasColumnName("LeadMinutes");

                            b1.HasKey("ReminderId");

                            b1.ToTable("Reminders");

                            b1.WithOwner()
                                .HasForeignKey("ReminderId");
                        });

                    b.OwnsOne("TaxVision.Reminder.Domain.ValueObjects.ReminderSubject", "Subject", b1 =>
                        {
                            b1.Property<Guid>("ReminderId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Body")
                                .HasMaxLength(2000)
                                .HasColumnType("nvarchar(2000)")
                                .HasColumnName("Body");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Title");

                            b1.HasKey("ReminderId");

                            b1.ToTable("Reminders");

                            b1.WithOwner()
                                .HasForeignKey("ReminderId");
                        });

                    b.OwnsOne("TaxVision.Reminder.Domain.ValueObjects.ReminderTarget", "Target", b1 =>
                        {
                            b1.Property<Guid>("ReminderId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Category")
                                .HasColumnType("int")
                                .HasColumnName("Category");

                            b1.Property<Guid?>("TargetId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("TargetId");

                            b1.HasKey("ReminderId");

                            b1.HasIndex("Category", "TargetId")
                                .HasDatabaseName("IX_Reminders_Category_TargetId");

                            b1.ToTable("Reminders");

                            b1.WithOwner()
                                .HasForeignKey("ReminderId");
                        });

                    b.Navigation("Schedule")
                        .IsRequired();

                    b.Navigation("Subject")
                        .IsRequired();

                    b.Navigation("Target")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
